// Focused quick-reply window for bwoinking a specific player from the info panel.
// Shows only the chat history for one player and a text input.
// Avoids the full admin panel player list, preventing accidental mis-sends.
using Content.Client.Administration.Systems;
using Content.Client.UserInterface.Controls;
using Content.Client.UserInterface.Systems.Bwoink;
using Content.Shared.Administration;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.IoC;
using Robust.Shared.Network;
using Robust.Shared.Utility;

namespace Content.Client._Misfits.Administration.UI;

[GenerateTypedNameReferences]
public sealed partial class QuickBwoinkWindow : FancyWindow
{
    [Dependency] private readonly IEntitySystemManager _entitySysMan = default!;
    [Dependency] private readonly IUserInterfaceManager _uiMan = default!;

    private readonly BwoinkSystem _bwoinkSys;
    private readonly NetUserId _targetUserId;
    private readonly string _targetName;

    public QuickBwoinkWindow(NetUserId targetUserId, string targetName)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _bwoinkSys = _entitySysMan.GetEntitySystem<BwoinkSystem>();
        _targetUserId = targetUserId;
        _targetName = targetName;

        Title = Loc.GetString("ticket-system-quick-reply-title", ("player", _targetName));

        // Show who we're talking to
        var label = new FormattedMessage();
        label.AddMarkup($"[bold]{Loc.GetString("ticket-system-quick-reply-target", ("player", FormattedMessage.EscapeText(_targetName)))}[/bold]");
        TargetLabel.SetMessage(label);

        // Wire input
        InputLine.OnTextEntered += OnTextEntered;

        // Listen for incoming messages on this channel
        _bwoinkSys.OnBwoinkTextMessageRecieved += OnBwoinkMessage;
    }

    private void OnTextEntered(LineEdit.LineEditEventArgs args)
    {
        if (string.IsNullOrWhiteSpace(args.Text))
            return;

        _bwoinkSys.Send(_targetUserId, args.Text, playSound: true);
        InputLine.Clear();
    }

    private void OnBwoinkMessage(object? sender, SharedBwoinkSystem.BwoinkTextMessage message)
    {
        // Only show messages for this channel
        if (message.UserId != _targetUserId)
            return;

        var formatted = new FormattedMessage(1);
        formatted.AddMarkup($"[color=gray]{message.SentAt.ToShortTimeString()}[/color] {message.Text}");
        ChatOutput.AddMessage(formatted);
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);
        _bwoinkSys.OnBwoinkTextMessageRecieved -= OnBwoinkMessage;
    }
}
