// #Misfits Add — Standalone ticket log window showing all current-round tickets.
// Opened from the Staff tab button in the Admin Menu.
using System.Linq;
using Content.Client.Administration.Systems;
using Content.Shared._Misfits.Administration;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.IoC;
using Robust.Shared.Utility;

namespace Content.Client._Misfits.Administration.UI;

[GenerateTypedNameReferences]
public sealed partial class TicketLogWindow : DefaultWindow
{
    [Dependency] private readonly IEntitySystemManager _entitySystem = default!;

    private readonly Dictionary<int, HelpTicketInfo> _tickets = new();
    private readonly BwoinkSystem _bwoinkSys;

    public TicketLogWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _bwoinkSys = _entitySystem.GetEntitySystem<BwoinkSystem>();

        _bwoinkSys.OnTicketUpdated += OnTicketUpdated;
        _bwoinkSys.OnTicketListReceived += OnTicketListReceived;

        RefreshTickets.OnPressed += _ => _bwoinkSys.RequestTicketList();

        // Seed from cached data so the list is populated immediately,
        // even if the server push arrived before this window was opened.
        foreach (var (_, ticket) in _bwoinkSys.CachedTickets)
            _tickets[ticket.TicketId] = ticket;
        RebuildList();

        // Also request a fresh list from the server to ensure sync
        _bwoinkSys.RequestTicketList();
    }

    private void OnTicketUpdated(HelpTicketInfo ticket)
    {
        // #Misfits Fix — guard against events firing after the window is disposed.
        if (Disposed)
            return;

        _tickets[ticket.TicketId] = ticket;
        RebuildList();
    }

    private void OnTicketListReceived(List<HelpTicketInfo> tickets)
    {
        // #Misfits Fix — guard against events firing after the window is disposed.
        if (Disposed)
            return;

        // Full list sync is authoritative for this round.
        _tickets.Clear();
        foreach (var t in tickets)
            _tickets[t.TicketId] = t;

        RebuildList();
    }

    private void RebuildList()
    {
        TicketListContainer.RemoveAllChildren();

        // Open first, then claimed, then resolved; newest within each group
        var sorted = _tickets.Values
            .OrderBy(t => t.Status)
            .ThenByDescending(t => t.CreatedAt);

        foreach (var ticket in sorted)
        {
            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                SeparationOverride = 4,
            };

            row.AddChild(new Label { Text = $"#{ticket.TicketId}", MinWidth = 60 });
            row.AddChild(new Label { Text = ticket.PlayerName, MinWidth = 140 });

            var statusLabel = new RichTextLabel { MinWidth = 120 };
            var statusMsg = new FormattedMessage();
            var (color, text) = ticket.Status switch
            {
                HelpTicketStatus.Open => ("red", Loc.GetString("ticket-system-status-open")),
                HelpTicketStatus.Claimed => ("yellow", Loc.GetString("ticket-system-status-claimed", ("role", ticket.Type == HelpTicketType.AdminHelp ? "Admin" : "Mentor"), ("admin", ticket.ClaimedByName ?? "?"))),
                // #Misfits Change — show which admin resolved the ticket
                HelpTicketStatus.Resolved => ("green", Loc.GetString("ticket-system-status-resolved", ("role", ticket.Type == HelpTicketType.AdminHelp ? "Admin" : "Mentor"), ("admin", ticket.ResolvedByName ?? "?"))),
                _ => ("gray", "Unknown"),
            };
            statusMsg.AddMarkup($"[color={color}]{FormattedMessage.EscapeText(text)}[/color]");
            statusLabel.SetMessage(statusMsg);
            row.AddChild(statusLabel);

            row.AddChild(new Label { Text = ticket.ClaimedByName ?? "—", MinWidth = 120 });
            // #Misfits Add — resolved-by column
            row.AddChild(new Label { Text = ticket.ResolvedByName ?? "—", MinWidth = 120 });
            // #Misfits Add — duration column (time from creation to resolution)
            var durationText = ticket.ResolvedAt.HasValue
                ? (ticket.ResolvedAt.Value - ticket.CreatedAt).ToString(@"hh\:mm\:ss")
                : "—";
            row.AddChild(new Label { Text = durationText, MinWidth = 80 });
            row.AddChild(new Label { Text = ticket.CreatedAt.ToString("HH:mm:ss"), MinWidth = 100 });

            TicketListContainer.AddChild(row);
        }
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        _bwoinkSys.OnTicketUpdated -= OnTicketUpdated;
        _bwoinkSys.OnTicketListReceived -= OnTicketListReceived;
    }
}
