// #Misfits Add — Toast notification popup for ticket events.
// Displayed in the top-right corner and auto-dismisses after a few seconds.
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._Misfits.Administration.UI;

[GenerateTypedNameReferences]
public sealed partial class TicketToastPopup : PanelContainer
{
    /// <summary>How long the toast stays visible (seconds).</summary>
    private const float DisplayDuration = 6f;

    private float _elapsed;

    public TicketToastPopup()
    {
        RobustXamlLoader.Load(this);
        // #Misfits Add — StyleBoxFlat cannot be used in SS14 XAML, so set it here instead
        PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex("#1a1a2eDD"),
            BorderColor = Color.FromHex("#e94560"),
            BorderThickness = new Thickness(1),
            ContentMarginLeftOverride = 10,
            ContentMarginRightOverride = 10,
            ContentMarginTopOverride = 8,
            ContentMarginBottomOverride = 8,
        };
    }

    /// <summary>
    /// Configure the toast content and add it to the UI tree.
    /// </summary>
    public void Show(string title, string body)
    {
        var titleMsg = new FormattedMessage();
        // #Misfits Fix — escape title/body text to prevent player names containing
        // bracket characters (e.g. "[Admin]") from crashing the markup parser.
        titleMsg.AddMarkup($"[bold][color=#e94560]{FormattedMessage.EscapeText(title)}[/color][/bold]");
        ToastTitle.SetMessage(titleMsg);

        var bodyMsg = new FormattedMessage();
        bodyMsg.AddMarkup(FormattedMessage.EscapeText(body));
        ToastMessage.SetMessage(bodyMsg);

        _elapsed = 0f;

        // Attach to the window root in the top-right corner
        UserInterfaceManager.PopupRoot.AddChild(this);
        LayoutContainer.SetAnchorPreset(this, LayoutContainer.LayoutPreset.TopRight);
        LayoutContainer.SetMarginRight(this, -10f);
        LayoutContainer.SetMarginTop(this, 60f);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        _elapsed += args.DeltaSeconds;
        if (_elapsed >= DisplayDuration)
        {
            Orphan();
            Dispose();
        }
    }
}
