// #Misfits Change - Whitelist Viewer admin panel code-behind
using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._Misfits.Administration;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Misfits.Administration.UI;

[GenerateTypedNameReferences]
public sealed partial class WhitelistViewWindow : FancyWindow
{
    public Action? OnRefresh;

    private List<string> _allCkeys = new();

    public WhitelistViewWindow()
    {
        RobustXamlLoader.Load(this);

        RefreshButton.OnPressed += _ => OnRefresh?.Invoke();
        FilterBox.OnTextChanged += _ => ApplyFilter();
    }

    public void HandleState(WhitelistViewEuiState state)
    {
        _allCkeys = state.WhitelistedCkeys;
        ApplyFilter();
    }

    private void ApplyFilter()
    {
        var filter = FilterBox.Text.Trim().ToLower();
        PlayerList.RemoveAllChildren();

        var visible = string.IsNullOrEmpty(filter)
            ? _allCkeys
            : _allCkeys.Where(c => c.ToLower().Contains(filter)).ToList();

        CountLabel.Text = $"Whitelisted players: {_allCkeys.Count}" +
                          (visible.Count != _allCkeys.Count ? $" ({visible.Count} shown)" : "");

        foreach (var ckey in visible)
        {
            PlayerList.AddChild(new Label
            {
                Text = ckey,
                HorizontalExpand = true,
            });
        }
    }
}
