// #Misfits Change - Staff Panel tab: quick action buttons + Audit Log + Activity Log + Banlist (Round Ticket Stats removed)
using Content.Client._Misfits.Administration.UI;
using Content.Client._Misfits.Administration.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Misfits.Administration.UI.Tabs;

[GenerateTypedNameReferences]
public sealed partial class StaffTab : Control
{
    private TicketAuditLogWindow? _auditLogWindow;

    public StaffTab()
    {
        RobustXamlLoader.Load(this);

        // Audit log button — opens the persistent DB-backed ticket audit window (cross-round)
        OpenAuditLog.OnPressed += _ =>
        {
            if (_auditLogWindow is { Disposed: false })
            {
                _auditLogWindow.MoveToFront();
                return;
            }

            _auditLogWindow = new TicketAuditLogWindow();
            _auditLogWindow.OnClose += () => _auditLogWindow = null;
            _auditLogWindow.OpenCentered();
        };

        // Activity log button — sends a net message to the server which opens AdminLogsEui
        // pre-filtered to High/Extreme admin-action types (Verb, AdminMessage, Spawn, Delete, Teleport, etc.)
        var entMan = IoCManager.Resolve<IEntityManager>();
        var activitySys = entMan.System<MisfitsAdminActivityClientSystem>();
        OpenActivityLog.OnPressed += _ => activitySys.RequestActivityLog();
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);
        _auditLogWindow?.Close();
    }
}
