// #Misfits Add - Dedicated ticket stats tab showing per-round admin and mentor ticket counts
using System.Linq;
using Content.Client._Misfits.Administration.Systems;
using Content.Client.Administration.Systems;
using Content.Shared._Misfits.Administration;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.Localization;
using Robust.Shared.Maths;
using Robust.Shared.Timing;

namespace Content.Client._Misfits.Administration.UI.Tabs;

[GenerateTypedNameReferences]
public sealed partial class TicketStatsTab : Control
{
    // Ticket data from both systems, keyed by (Type, TicketId)
    private readonly Dictionary<(HelpTicketType, int), HelpTicketInfo> _tickets = new();

    // Dirty flag — batches incoming ticket updates until the next frame,
    // but the actual rebuild must happen before the control tree is traversed.
    private bool _statsDirty;

    private BwoinkSystem? _bwoinkSys;
    private MentorHelpSystem? _mentorSys;

    public TicketStatsTab()
    {
        RobustXamlLoader.Load(this);

        // Style the stats panel background
        StatsPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = new Color(30, 30, 50, 200),
            ContentMarginLeftOverride = 6,
            ContentMarginRightOverride = 6,
            ContentMarginTopOverride = 4,
            ContentMarginBottomOverride = 4,
        };

        // Subscribe to ticket events from both admin-help and mentor-help systems
        var entitySysMan = IoCManager.Resolve<IEntitySystemManager>();

        _bwoinkSys = entitySysMan.GetEntitySystem<BwoinkSystem>();
        _bwoinkSys.OnTicketUpdated += OnAdminTicketUpdated;
        _bwoinkSys.OnTicketListReceived += OnAdminTicketList;
        _bwoinkSys.RequestTicketList();

        _mentorSys = entitySysMan.GetEntitySystem<MentorHelpSystem>();
        _mentorSys.OnTicketUpdated += OnMentorTicketUpdated;
        _mentorSys.OnTicketListReceived += OnMentorTicketList;
        _mentorSys.RequestTicketList();

        // Initial render with empty data
        RefreshStats();
    }

    private void OnAdminTicketUpdated(HelpTicketInfo ticket)
    {
        // #Misfits Fix — guard against events firing on a disposed tab.
        if (Disposed) return;
        _tickets[(HelpTicketType.AdminHelp, ticket.TicketId)] = ticket;
        _statsDirty = true;
    }

    private void OnAdminTicketList(List<HelpTicketInfo> tickets)
    {
        if (Disposed) return;
        foreach (var t in tickets)
            _tickets[(HelpTicketType.AdminHelp, t.TicketId)] = t;
        _statsDirty = true;
    }

    private void OnMentorTicketUpdated(HelpTicketInfo ticket)
    {
        if (Disposed) return;
        _tickets[(HelpTicketType.MentorHelp, ticket.TicketId)] = ticket;
        _statsDirty = true;
    }

    private void OnMentorTicketList(List<HelpTicketInfo> tickets)
    {
        if (Disposed) return;
        foreach (var t in tickets)
            _tickets[(HelpTicketType.MentorHelp, t.TicketId)] = t;
        _statsDirty = true;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        if (_statsDirty)
        {
            _statsDirty = false;
            RefreshStats();
        }

        base.FrameUpdate(args);
    }

    /// <summary>
    /// Recomputes all stats from the in-memory ticket dictionary and updates labels + grid.
    /// </summary>
    private void RefreshStats()
    {
        var all = _tickets.Values.ToList();

        // Split stats by ticket type
        var adminList = _tickets.Where(kv => kv.Key.Item1 == HelpTicketType.AdminHelp).Select(kv => kv.Value).ToList();
        var mentorList = _tickets.Where(kv => kv.Key.Item1 == HelpTicketType.MentorHelp).Select(kv => kv.Value).ToList();

        // Update admin row
        AdminTotalLabel.Text = Loc.GetString("misfits-staff-stats-total", ("count", adminList.Count));
        AdminOpenLabel.Text = Loc.GetString("misfits-staff-stats-open", ("count", adminList.Count(t => t.Status == HelpTicketStatus.Open)));
        AdminClaimedLabel.Text = Loc.GetString("misfits-staff-stats-claimed", ("count", adminList.Count(t => t.Status == HelpTicketStatus.Claimed)));
        AdminResolvedLabel.Text = Loc.GetString("misfits-staff-stats-resolved", ("count", adminList.Count(t => t.Status == HelpTicketStatus.Resolved)));

        // Update mentor row
        MentorTotalLabel.Text = Loc.GetString("misfits-staff-stats-total", ("count", mentorList.Count));
        MentorOpenLabel.Text = Loc.GetString("misfits-staff-stats-open", ("count", mentorList.Count(t => t.Status == HelpTicketStatus.Open)));
        MentorClaimedLabel.Text = Loc.GetString("misfits-staff-stats-claimed", ("count", mentorList.Count(t => t.Status == HelpTicketStatus.Claimed)));
        MentorResolvedLabel.Text = Loc.GetString("misfits-staff-stats-resolved", ("count", mentorList.Count(t => t.Status == HelpTicketStatus.Resolved)));

        // Color open counts red when there are unclaimed tickets
        AdminOpenLabel.FontColorOverride = adminList.Any(t => t.Status == HelpTicketStatus.Open) ? Color.Red : null;
        MentorOpenLabel.FontColorOverride = mentorList.Any(t => t.Status == HelpTicketStatus.Open) ? Color.Red : null;

        // Average resolution time (combined, only for resolved tickets with timestamps)
        var resolvedWithTime = all
            .Where(t => t.Status == HelpTicketStatus.Resolved && t.ResolvedAt.HasValue)
            .ToList();

        string avgTimeStr;
        if (resolvedWithTime.Count > 0)
        {
            var avgSeconds = resolvedWithTime
                .Average(t => (t.ResolvedAt!.Value - t.CreatedAt).TotalSeconds);
            var avgSpan = TimeSpan.FromSeconds(avgSeconds);
            avgTimeStr = avgSpan.TotalMinutes >= 1
                ? $"{avgSpan.Minutes}m {avgSpan.Seconds}s"
                : $"{avgSpan.Seconds}s";
        }
        else
        {
            avgTimeStr = Loc.GetString("misfits-staff-stats-na");
        }

        AvgResolutionLabel.Text = Loc.GetString("misfits-staff-stats-avg-time", ("time", avgTimeStr));

        // Build per-staff breakdown
        // Collect all staff who claimed or resolved at least one ticket
        var staffEntries = new Dictionary<string, (int claimedCount, int resolvedCount)>();

        foreach (var ticket in all)
        {
            if (ticket.ClaimedByName != null)
            {
                if (!staffEntries.TryGetValue(ticket.ClaimedByName, out var entry))
                    entry = (0, 0);
                entry.claimedCount++;
                staffEntries[ticket.ClaimedByName] = entry;
            }

            if (ticket.ResolvedByName != null && ticket.ResolvedByName != "System")
            {
                if (!staffEntries.TryGetValue(ticket.ResolvedByName, out var entry))
                    entry = (0, 0);
                entry.resolvedCount++;
                staffEntries[ticket.ResolvedByName] = entry;
            }
        }

        // Rebuild the grid
        StaffGrid.RemoveAllChildren();

        if (staffEntries.Count == 0)
        {
            // No staff activity yet — show a hint
            var noData = new Label
            {
                Text = Loc.GetString("misfits-staff-stats-no-activity"),
                StyleClasses = { "LabelSubText" },
            };
            StaffGrid.AddChild(noData);
            return;
        }

        // Header row
        AddGridHeader(Loc.GetString("misfits-staff-stats-col-name"), 120);
        AddGridHeader(Loc.GetString("misfits-staff-stats-col-claimed"), 90);
        AddGridHeader(Loc.GetString("misfits-staff-stats-col-resolved"), 90);
        AddGridHeader(Loc.GetString("misfits-staff-stats-col-ratio"), 70);

        // Data rows sorted by total activity descending
        var total = all.Count;
        foreach (var (name, (claimedC, resolvedC)) in staffEntries.OrderByDescending(e => e.Value.claimedCount + e.Value.resolvedCount))
        {
            var ratio = total > 0
                ? $"{(double)(claimedC + resolvedC) / total * 100:F0}%"
                : "0%";

            AddGridCell(name, 120);
            AddGridCell(claimedC.ToString(), 90);
            AddGridCell(resolvedC.ToString(), 90);
            AddGridCell(ratio, 70);
        }
    }

    private void AddGridHeader(string text, int minWidth = 80)
    {
        StaffGrid.AddChild(new Label
        {
            Text = text,
            StyleClasses = { "LabelSubText" },
            FontColorOverride = Color.LightGray,
            MinWidth = minWidth,
        });
    }

    private void AddGridCell(string text, int minWidth = 80)
    {
        StaffGrid.AddChild(new Label
        {
            Text = text,
            StyleClasses = { "LabelSubText" },
            MinWidth = minWidth,
        });
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        if (_bwoinkSys != null)
        {
            _bwoinkSys.OnTicketUpdated -= OnAdminTicketUpdated;
            _bwoinkSys.OnTicketListReceived -= OnAdminTicketList;
        }

        if (_mentorSys != null)
        {
            _mentorSys.OnTicketUpdated -= OnMentorTicketUpdated;
            _mentorSys.OnTicketListReceived -= OnMentorTicketList;
        }
    }
}
