// #Misfits Add - Code-behind for the scrollable role ban list control in the global ban list window
using System.Linq;
using Content.Client.Administration.UI.CustomControls;
using Content.Shared._Misfits.Administration.BanList;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Misfits.Administration.UI.BanListAll.RoleBans;

[GenerateTypedNameReferences]
public sealed partial class MisfitsRoleBanListAllControl : Control
{
    public event Action<MisfitsRoleBanListAllLine>? LineIdsClicked;
    public event Action<List<int>>? PardonRoleBans;

    public MisfitsRoleBanListAllControl()
    {
        RobustXamlLoader.Load(this);
    }

    /// <summary>
    /// Populates the list with the provided role ban entries, clearing any previous entries.
    /// </summary>
    public void SetRoleBans(List<MisfitsRoleBanEntry> bans)
    {
        // Remove all children after the header (index 0)
        for (var i = RoleBans.ChildCount - 1; i >= 1; i--)
        {
            RoleBans.GetChild(i).Dispose();
        }

        foreach (var group in bans.GroupBy(entry => entry.PlayerName, StringComparer.OrdinalIgnoreCase))
        {
            var activeIds = group
                .Where(entry => entry.Ban.Unban == null &&
                                (entry.Ban.ExpirationTime == null || entry.Ban.ExpirationTime > DateTimeOffset.UtcNow))
                .Select(entry => entry.Ban.Id)
                .Where(id => id.HasValue)
                .Select(id => id!.Value)
                .ToList();

            var playerGroup = new MisfitsRoleBanPlayerGroup(group.Key, activeIds);
            playerGroup.PardonPressed += ids => PardonRoleBans?.Invoke(ids);
            RoleBans.AddChild(playerGroup);

            foreach (var entry in group)
            {
                RoleBans.AddChild(new HSeparator());

                var line = new MisfitsRoleBanListAllLine(entry);
                line.IdsClicked += LineIdsClicked;
                RoleBans.AddChild(line);
            }
        }
    }
}
