using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using static Robust.Client.UserInterface.Controls.BaseButton;

namespace Content.Client._Misfits.Administration.UI.BanListAll.RoleBans;

[GenerateTypedNameReferences]
public sealed partial class MisfitsRoleBanPlayerGroup : PanelContainer
{
    private readonly List<int> _activeBanIds;
    public event Action<List<int>>? PardonPressed;

    public MisfitsRoleBanPlayerGroup(string playerName, List<int> activeBanIds)
    {
        RobustXamlLoader.Load(this);
        _activeBanIds = activeBanIds;
        Player.Text = playerName;
        Count.Text = Loc.GetString("banlistall-roleban-active-count", ("count", activeBanIds.Count));
        Pardon.Disabled = activeBanIds.Count == 0;
        Pardon.OnPressed += OnPardonPressed;
    }

    private void OnPardonPressed(ButtonEventArgs args)
    {
        PardonPressed?.Invoke(_activeBanIds);
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);
        Pardon.OnPressed -= OnPardonPressed;
        PardonPressed = null;
    }
}
