// #Misfits Add — Code-behind for SmokeSignalWindow.xaml.
// Provides a text input for the smoke signal message and exposes Send/Cancel callbacks.

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Misfits.SmokeSignal;

/// <summary>
/// Simple window containing a text input for composing a smoke signal message.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class SmokeSignalWindow : DefaultWindow
{
    /// <summary>
    /// Invoked when the player confirms the message. Carries the typed text.
    /// </summary>
    public event Action<string>? OnSend;

    public SmokeSignalWindow()
    {
        RobustXamlLoader.Load(this);

        // Send on button press
        SendButton.OnPressed += _ =>
        {
            var text = MessageInput.Text.Trim();
            if (text.Length == 0)
                return;

            OnSend?.Invoke(text);
            Close();
        };

        // Send on Enter key in the input field
        MessageInput.OnTextEntered += e =>
        {
            var text = e.Text.Trim();
            if (text.Length == 0)
                return;

            OnSend?.Invoke(text);
            Close();
        };

        CancelButton.OnPressed += _ => Close();
    }

    /// <summary>
    /// Clamps the input field's max character count.
    /// </summary>
    public void SetMaxLength(int maxLength)
    {
        // #Misfits Fix - LineEdit.MaxLength removed in newer RTB; enforce via OnTextChanged instead
        MessageInput.OnTextChanged += e =>
        {
            if (e.Text.Length > maxLength)
                MessageInput.Text = e.Text[..maxLength];
        };
    }
}
