# #Misfits Add - Enclave Scientist role (mid-tier science).
# #Misfits Change - Expanded species, added rank pin, tiered access, playtime gate.

- type: job
  id: EnclaveScientist
  setPreference: true
  jobWhitelistBypassesRoleTimers: true # #Misfits Change
  weight: 106
  displayWeight: 125
  overrideConsoleVisibility: false
  canBeAntag: false
  name: job-name-enclave-scientist
  description: job-description-enclave-scientist
  playTimeTracker: EnclaveScientist
  requirements:
    - !type:CharacterSpeciesRequirement
      species:
      - Human
      - Ghoul
    - !type:CharacterDepartmentTimeRequirement # #Misfits Tweak - BoS-equivalent specialist faction timelock
      department: Enclave
      min: 28800 # 8 hours
  startingGear: EnclaveScientistGear
  icon: "JobIconEnclaveScientist"
  supervisors: job-supervisors-enclave-scientist
  alwaysUseSpawner: true
  accessGroups:
  - EnclaveScientist
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - Enclave
          - Wastelander
      - type: ReplacementAccent
        accent: n14Enclave
      - type: CPRTraining
  - !type:AddTraitSpecial # #Misfits Add - Enclave scientists are issued an Enclave Eyebot companion
    traits: [ MisfitsPetEyebotEnclave ]

- type: startingGear
  id: EnclaveScientistGear
  equipment:
    wallet: N14Wallet
    head: N14ClothingHeadHatEnclaveScientist
    back: N14ClothingBackpackSatchelMilitary
    jumpsuit: N14ClothingUniformJumpsuitEnclave
    outerClothing: N14ClothingOuterRadSuitEnclave
    shoes: N14ClothingBootsLeatherFilled
    neck: ClothingNeckPinEnclaveScientist
    belt: ClothingBeltMilitary
    ears: N14ClothingHeadsetEnclave
    pocket2: EnclaveScientistloadoutkits
    id: N14EnclaveNoncombatPipboy
  satchel: N14ClothingBackpackSatchelMilitaryFilled
  storage:
    back:
    - N14BoxPlasticFilledMilitary

- type: playTimeTracker
  id: EnclaveScientist
