// #Misfits Change - Mentor Help window code-behind
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Misfits.Administration.UI.MentorHelp;

[GenerateTypedNameReferences]
public sealed partial class MentorHelpWindow : DefaultWindow
{
    public MentorHelpWindow()
    {
        RobustXamlLoader.Load(this);

        MentorHelp.ChannelSelector.OnSelectionChanged += sel =>
        {
            if (sel is null)
            {
                Title = "Mentor Message";
                return;
            }

            Title = $"{sel.CharacterName} / {sel.Username}";

            if (sel.OverallPlaytime != null)
            {
                Title += $" | Playtime: {sel.PlaytimeString}";
            }
        };

        OnOpen += () =>
        {
            MentorHelp.ChannelSelector.StopFiltering();
            MentorHelp.PopulateList();
        };
    }
}
