// #Misfits Add — Code-behind for SpiritBoardResponseWindow.xaml.
// Wires all response buttons to a single OnResponse callback.
// Closes after any selection except alphabet letters (those stay open for chaining).

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Misfits.SpiritBoard;

/// <summary>
/// Ghost response selection window for the Spirit Board séance.
/// Fires <see cref="OnResponse"/> with the selected token.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class SpiritBoardResponseWindow : DefaultWindow
{
    /// <summary>
    /// Invoked when the ghost picks a response. Carries the token string (e.g. "YES", "A").
    /// </summary>
    public event Action<string>? OnResponse;

    public SpiritBoardResponseWindow()
    {
        RobustXamlLoader.Load(this);

        // Primary choices — close the window after selection
        YesButton.OnPressed     += _ => Pick("YES",     close: true);
        NoButton.OnPressed      += _ => Pick("NO",      close: true);
        MaybeButton.OnPressed   += _ => Pick("MAYBE",   close: true);
        GoodbyeButton.OnPressed += _ => Pick("GOODBYE", close: true);

        // Alphabet buttons — stay open so the ghost can spell things out
        BtnA.OnPressed += _ => Pick("A"); BtnB.OnPressed += _ => Pick("B");
        BtnC.OnPressed += _ => Pick("C"); BtnD.OnPressed += _ => Pick("D");
        BtnE.OnPressed += _ => Pick("E"); BtnF.OnPressed += _ => Pick("F");
        BtnG.OnPressed += _ => Pick("G"); BtnH.OnPressed += _ => Pick("H");
        BtnI.OnPressed += _ => Pick("I"); BtnJ.OnPressed += _ => Pick("J");
        BtnK.OnPressed += _ => Pick("K"); BtnL.OnPressed += _ => Pick("L");
        BtnM.OnPressed += _ => Pick("M"); BtnN.OnPressed += _ => Pick("N");
        BtnO.OnPressed += _ => Pick("O"); BtnP.OnPressed += _ => Pick("P");
        BtnQ.OnPressed += _ => Pick("Q"); BtnR.OnPressed += _ => Pick("R");
        BtnS.OnPressed += _ => Pick("S"); BtnT.OnPressed += _ => Pick("T");
        BtnU.OnPressed += _ => Pick("U"); BtnV.OnPressed += _ => Pick("V");
        BtnW.OnPressed += _ => Pick("W"); BtnX.OnPressed += _ => Pick("X");
        BtnY.OnPressed += _ => Pick("Y"); BtnZ.OnPressed += _ => Pick("Z");
    }

    private void Pick(string token, bool close = false)
    {
        OnResponse?.Invoke(token);
        if (close)
            Close();
    }
}
