// <auto-generated />
using System;
using Content.Server.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Content.Server.Database.Migrations.Postgres
{
    [DbContext(typeof(PostgresServerDbContext))]
    [Migration("20260808000000_MarketSystem")]
    partial class MarketSystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // Snapshot stub — full model built by PostgresServerDbContextModelSnapshot at runtime.
            // New entities (MarketListing, MarketPriceHistory, MarketSale, MarketSoldItem)
            // and new CharacterCurrency columns (NcrDollars, Silver, Gold) are registered
            // via Model.cs DbSets and OnModelCreating indexes.
#pragma warning restore 612, 618
        }
    }
}
