using Content.Client.UserInterface.Controls;
using Content.Shared._Misfits.TreeOfLife;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Misfits.TreeOfLife;

[GenerateTypedNameReferences]
public sealed partial class TreeOfLifeRitesWindow : FancyWindow
{
    public event Action<TreeOfLifeRite>? SelectRite;

    public TreeOfLifeRitesWindow()
    {
        RobustXamlLoader.Load(this);
        ReturningButton.OnPressed += _ => SelectRite?.Invoke(TreeOfLifeRite.Returning);
        HearthButton.OnPressed += _ => SelectRite?.Invoke(TreeOfLifeRite.Hearth);
    }

    public void SetState(TreeOfLifeRitesState state)
    {
        var rite = state.ActiveRite switch
        {
            TreeOfLifeRite.Returning => Loc.GetString("tree-of-life-rite-returning"),
            TreeOfLifeRite.Hearth => Loc.GetString("tree-of-life-rite-hearth"),
            _ => Loc.GetString("tree-of-life-rite-none"),
        };

        CurrentRite.Text = Loc.GetString("tree-of-life-rites-current", ("rite", rite));
        Cooldown.Text = state.SecondsUntilChange > 0
            ? Loc.GetString("tree-of-life-rites-cooldown", ("seconds", state.SecondsUntilChange))
            : Loc.GetString("tree-of-life-rites-ready");
        ReturningButton.Disabled = !state.CanSelect;
        HearthButton.Disabled = !state.CanSelect;
    }
}
