// #Misfits Change - Currency wallet window
using Content.Shared._Misfits.Currency.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Misfits.Currency;

[GenerateTypedNameReferences]
public sealed partial class CurrencyWalletWindow : DefaultWindow
{
    public event Action<CurrencyType, int>? OnWithdrawRequest;
    public event Action? OnDepositInHandRequest;

    public CurrencyWalletWindow()
    {
        RobustXamlLoader.Load(this);

        DepositInHandButton.OnPressed += _ => OnDepositInHandRequest?.Invoke();
        BottlecapsWithdraw.OnPressed += _ => TryWithdraw(CurrencyType.Bottlecaps, BottlecapsAmount);
        NcrDollarsWithdraw.OnPressed += _ => TryWithdraw(CurrencyType.NCRDollars, NcrDollarsAmount);
        LegionDenariiWithdraw.OnPressed += _ => TryWithdraw(CurrencyType.LegionDenarii, LegionDenariiAmount);
        PrewarMoneyWithdraw.OnPressed += _ => TryWithdraw(CurrencyType.PrewarMoney, PrewarMoneyAmount);
    }

    public void UpdateState(int bottlecaps, int ncrDollars, int legionDenarii, int prewarMoney)
    {
        BottlecapsLabel.Text = bottlecaps.ToString();
        NcrDollarsLabel.Text = ncrDollars.ToString();
        LegionDenariiLabel.Text = legionDenarii.ToString();
        PrewarMoneyLabel.Text = prewarMoney.ToString();
    }

    private void TryWithdraw(CurrencyType type, Robust.Client.UserInterface.Controls.LineEdit lineEdit)
    {
        if (!int.TryParse(lineEdit.Text, out var amount) || amount <= 0)
            return;

        OnWithdrawRequest?.Invoke(type, amount);
        lineEdit.Text = string.Empty;
    }
}
