// #Misfits Add - PipBoy Groups program code-behind (split from PipBoy Hub).
// Handles group creation/joining, group chat, waypoints, encryption, and map tracking.
// Collapsible group panels with red flash notification on new activity.
using System.Linq;
using System.Numerics;
using Content.Shared._Misfits.PipBoy;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Misfits.PipBoy;

[GenerateTypedNameReferences]
public sealed partial class PipBoyGroupsUiFragment : BoxContainer
{
    public event Action<PipBoyHubMessageType, uint?, uint?, string?>? OnSendMessage;

    private uint? _currentGroupId;

    // #Misfits Add - Track collapsed state per group and last-seen message count for flash notifications
    private readonly HashSet<uint> _collapsedGroups = new();
    private readonly Dictionary<uint, int> _lastSeenMessageCount = new();

    public PipBoyGroupsUiFragment()
    {
        RobustXamlLoader.Load(this);

        // Create group — #Misfits Change: support user-chosen custom group ID
        GroupCreateBtn.OnPressed += _ =>
        {
            if (!string.IsNullOrWhiteSpace(GroupNameInput.Text))
            {
                // Pack custom ID into the content string: "name\0customId"
                var name = GroupNameInput.Text.Trim();
                var customIdText = GroupCustomIdInput.Text?.Trim();
                string content;
                if (!string.IsNullOrEmpty(customIdText) && uint.TryParse(customIdText, out var cid) && cid > 0)
                    content = $"{name}\0{cid}";
                else
                    content = name;

                OnSendMessage?.Invoke(PipBoyHubMessageType.GroupCreate, null, null, content);
                GroupNameInput.Text = string.Empty;
                GroupCustomIdInput.Text = string.Empty;
            }
        };

        // Join group
        GroupJoinBtn.OnPressed += _ =>
        {
            if (uint.TryParse(GroupIdInput.Text, out var gid) && gid > 0)
            {
                var password = string.IsNullOrEmpty(GroupPasswordInput.Text) ? null : GroupPasswordInput.Text;
                OnSendMessage?.Invoke(PipBoyHubMessageType.GroupJoin, null, gid, password);
                GroupIdInput.Text = string.Empty;
                GroupPasswordInput.Text = string.Empty;
            }
        };

        // Send group message
        GroupSendBtn.OnPressed += _ => SendGroupMessage();
        GroupMessageInput.OnTextEntered += _ => SendGroupMessage();

        // Waypoints
        WaypointAddBtn.OnPressed += _ =>
        {
            if (_currentGroupId != null && !string.IsNullOrWhiteSpace(WaypointLabelInput.Text))
            {
                OnSendMessage?.Invoke(PipBoyHubMessageType.GroupAddWaypoint, null, _currentGroupId, WaypointLabelInput.Text);
                WaypointLabelInput.Text = string.Empty;
            }
        };

        // Group encryption
        GroupSetPasswordBtn.OnPressed += _ =>
        {
            if (_currentGroupId != null)
            {
                var pw = GroupEncryptPasswordInput.Text?.Trim();
                OnSendMessage?.Invoke(PipBoyHubMessageType.GroupSetPassword, null, _currentGroupId, pw);
                GroupEncryptPasswordInput.Text = string.Empty;
            }
        };
    }

    private void SendGroupMessage()
    {
        if (string.IsNullOrWhiteSpace(GroupMessageInput.Text))
            return;

        OnSendMessage?.Invoke(PipBoyHubMessageType.GroupSendMessage, null, _currentGroupId, GroupMessageInput.Text);
        GroupMessageInput.Text = string.Empty;
    }

    public void UpdateState(PipBoyHubUiState state)
    {
        OwnNumberLabel.Text = $"#{state.OwnNumber:D4}";

        var locked = state.IsLocked;
        LockedLabel.Visible = locked;
        MainPanel.Visible = !locked;
        if (locked)
            return;

        UpdateGroups(state);
    }

    private void UpdateGroups(PipBoyHubUiState state)
    {
        GroupList.RemoveAllChildren();

        var hasGroups = state.Groups.Count > 0;
        NoGroupsLabel.Visible = !hasGroups;
        if (!hasGroups)
            GroupList.AddChild(NoGroupsLabel);

        foreach (var group in state.Groups)
        {
            // #Misfits Add - Detect new activity for flash notification
            var hasNewActivity = false;
            if (_lastSeenMessageCount.TryGetValue(group.GroupId, out var lastCount))
            {
                // If this group is selected, update the seen count; otherwise, check for new msgs
                if (state.SelectedGroupId == group.GroupId)
                    _lastSeenMessageCount[group.GroupId] = state.GroupMessages.Count;
                else if (state.Groups.FirstOrDefault(g => g.GroupId == group.GroupId).MemberCount != lastCount)
                    hasNewActivity = true; // member count changed = proxy for activity in non-selected groups
            }
            else
            {
                _lastSeenMessageCount[group.GroupId] = 0;
            }

            var isCollapsed = _collapsedGroups.Contains(group.GroupId);
            var isSelected = state.SelectedGroupId == group.GroupId;
            var encryptedTag = group.IsEncrypted ? " 🔒" : "";

            // #Misfits Add - Collapsible group entry: full-width toggle button
            var groupContainer = new BoxContainer
            {
                Orientation = LayoutOrientation.Vertical,
                HorizontalExpand = true,
                Margin = new Thickness(0, 0, 0, 4), // spacer between groups
            };

            var toggleBtn = new Button
            {
                Text = $"{(isCollapsed ? "▶" : "▼")} {group.GroupName}{encryptedTag} (ID:{group.GroupId}) [{group.MemberCount}]",
                HorizontalExpand = true,
                Modulate = hasNewActivity ? Color.FromHex("#FF4444") : (isSelected ? Color.FromHex("#88FF88") : Color.White),
            };
            var capturedGid = group.GroupId;
            toggleBtn.OnPressed += _ =>
            {
                if (_collapsedGroups.Contains(capturedGid))
                    _collapsedGroups.Remove(capturedGid);
                else
                    _collapsedGroups.Add(capturedGid);
                // #Misfits Change - Toggle collapse locally and select/deselect the group
                if (_collapsedGroups.Contains(capturedGid))
                    OnSendMessage?.Invoke(PipBoyHubMessageType.GroupSelect, null, null, null); // deselect
                else
                    OnSendMessage?.Invoke(PipBoyHubMessageType.GroupSelect, null, capturedGid, null); // select
            };
            groupContainer.AddChild(toggleBtn);

            // #Misfits Add - Controls row only visible when expanded
            if (!isCollapsed)
            {
                var controlsRow = new BoxContainer
                {
                    Orientation = LayoutOrientation.Horizontal,
                    HorizontalExpand = true,
                    Margin = new Thickness(0, 2, 0, 0),
                };

                var selectBtn = new Button
                {
                    Text = isSelected ? "● Active" : "Select",
                    HorizontalExpand = true,
                    Disabled = isSelected,
                    Margin = new Thickness(0, 0, 2, 0),
                };
                selectBtn.OnPressed += _ =>
                {
                    // Clear new-activity flash when selecting
                    _lastSeenMessageCount[capturedGid] = 0;
                    OnSendMessage?.Invoke(PipBoyHubMessageType.GroupSelect, null, capturedGid, null);
                };
                controlsRow.AddChild(selectBtn);

                var trackBtn = new Button
                {
                    Text = group.MapTrackingEnabled
                        ? Loc.GetString("pipboy-hub-tracking-on")
                        : Loc.GetString("pipboy-hub-tracking-off"),
                    MinWidth = 60,
                    Margin = new Thickness(0, 0, 2, 0),
                    ToolTip = Loc.GetString("pipboy-hub-toggle-tracking-tooltip"),
                };
                var capturedGid2 = group.GroupId;
                trackBtn.OnPressed += _ =>
                    OnSendMessage?.Invoke(PipBoyHubMessageType.GroupToggleMapTracking, null, capturedGid2, null);
                controlsRow.AddChild(trackBtn);

                var leaveBtn = new Button
                {
                    Text = Loc.GetString("pipboy-hub-group-leave"),
                    MinWidth = 50,
                };
                var capturedGid3 = group.GroupId;
                leaveBtn.OnPressed += _ =>
                    OnSendMessage?.Invoke(PipBoyHubMessageType.GroupLeave, null, capturedGid3, null);
                controlsRow.AddChild(leaveBtn);

                groupContainer.AddChild(controlsRow);
            }

            GroupList.AddChild(groupContainer);
        }

        _currentGroupId = state.SelectedGroupId;

        var hasSelected = state.SelectedGroupId != null;
        GroupMessagesScroll.Visible = hasSelected;
        GroupMessageInputRow.Visible = hasSelected;
        GroupChatTitle.Text = hasSelected
            ? state.Groups.FirstOrDefault(g => g.GroupId == state.SelectedGroupId).GroupName ?? ""
            : Loc.GetString("pipboy-hub-group-select-prompt");

        // Group tracking locations
        GroupTrackingPanel.Visible = hasSelected && state.GroupLocations.Count > 0;
        GroupTrackingList.RemoveAllChildren();
        foreach (var loc in state.GroupLocations)
        {
            GroupTrackingList.AddChild(new Label
            {
                Text = $"{loc.Name}: ({loc.X:F0}, {loc.Y:F0})",
                StyleClasses = { "LabelSubText" },
            });
        }

        // Group waypoints
        GroupWaypointsPanel.Visible = hasSelected;
        GroupWaypointsList.RemoveAllChildren();
        for (var i = 0; i < state.GroupWaypoints.Count; i++)
        {
            var wp = state.GroupWaypoints[i];
            var wpRow = new BoxContainer
            {
                Orientation = LayoutOrientation.Horizontal,
                HorizontalExpand = true,
            };
            wpRow.AddChild(new Label
            {
                Text = $"📍 {wp.Label} ({wp.X:F0}, {wp.Y:F0}) — {wp.SetByName}",
                HorizontalExpand = true,
                ClipText = true,
                StyleClasses = { "LabelSubText" },
            });
            var capturedIdx = i;
            var capturedGid4 = state.SelectedGroupId;
            var removeWpBtn = new Button { Text = "X", MinWidth = 22, Margin = new Thickness(2, 0, 0, 0) };
            removeWpBtn.OnPressed += _ =>
                OnSendMessage?.Invoke(PipBoyHubMessageType.GroupRemoveWaypoint, null, capturedGid4, capturedIdx.ToString());
            wpRow.AddChild(removeWpBtn);
            GroupWaypointsList.AddChild(wpRow);
        }

        // Encryption controls
        GroupEncryptionRow.Visible = hasSelected;

        // Radio status
        RadioStatusLabel.Visible = hasSelected;
        RadioStatusLabel.Text = state.HasRadioConnection
            ? Loc.GetString("pipboy-hub-radio-connected")
            : Loc.GetString("pipboy-hub-radio-disconnected");

        // Group messages
        GroupMessageList.RemoveAllChildren();
        foreach (var msg in state.GroupMessages)
        {
            var bubble = new BoxContainer
            {
                Orientation = LayoutOrientation.Vertical,
                HorizontalExpand = true,
                Margin = new Thickness(0, 1),
            };
            bubble.AddChild(new Label { Text = $"{msg.SenderName}:", StyleClasses = { "LabelSubText" } });
            bubble.AddChild(new Label { Text = msg.Content, HorizontalExpand = true });
            GroupMessageList.AddChild(bubble);
        }

        // Scroll to bottom
        if (GroupMessageList.Parent is ScrollContainer scroll)
            scroll.SetScrollValue(new Vector2(0, float.MaxValue));
    }
}
