# #Misfits Add - White Legs Storm Drummer prototype for the dedicated White Legs department.

- type: job
  id: WhiteLegsStormDrummer
  setPreference: false # #Misfits Change - White Legs is retained for compatibility, not character setup.
  weight: 30
  name: job-name-whitelegs-storm-drummer
  description: job-description-whitelegs-storm-drummer
  playTimeTracker: WhiteLegsStormDrummer
  whitelisted: true
  requirements:
  - !type:MinPlayersRequirement
    min: 0
  - !type:CharacterSpeciesRequirement
    species:
    - Human
    - Ghoul
  - !type:CharacterDepartmentTimeRequirement
    department: GreatKhans
    min: 28800 # 8 hours
  startingGear: WhiteLegsStormDrummerGear
  alwaysUseSpawner: true
  icon: "JobIconWhiteLegCaller"
  supervisors: job-supervisors-whitelegs
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - PlayerRaider

- type: startingGear
  id: WhiteLegsStormDrummerGear
  equipment:
    wallet: N14Wallet
    bandage: NCClothingBandageRaiders
    jumpsuit: M14ClothingUniformWhiteLegsUniform
    outerClothing: MisfitsClothingOuterWhiteLegsArmor
    shoes: N14ClothingShoesRaider
    neck: ClothingNeckBlackScarf
    head: N14ClothingHeadHatBeanie
    ears: MisfitsClothingHeadsetWastelandScrap
    back: N14ClothingBackpackMilitary
    suitstorage: N14WastelandTribalSpear
    pocket1: N14TribalKnife
  storage:
    back:
    - N14BoxPlasticFilledWastelander

- type: playTimeTracker
  id: WhiteLegsStormDrummer
