- type: job
  id: CaesarLegionAcolyteOfMars
  setPreference: true
  hideWithoutJobWhitelist: false  # visible in all menus regardless of whitelist
  overrideConsoleVisibility: true # force display in crew manifest + job picker
  hideIfPlaytimeRequirementsNotMet: false
  jobWhitelistBypassesRoleTimers: true
  weight: 160  # Underneath POM
  name: job-name-caesar-legion-Acolyte-of-mars
  description: job-description-caesar-legion-Acolyte-of-mars
  playTimeTracker: CaesarLegionAcolyteOfMars
  requirements:
    - !type:CharacterDepartmentTimeRequirement # Legion total timelock
      department: CaesarLegion
      min: 72000 # 20 hours
    - !type:CharacterSpeciesRequirement
      species:
        - Human
    - !type:CharacterSexRequirement
      sex: Female
    - !type:CharacterGenderRequirement
      gender: Female
  startingGear: CaesarLegionAcolyteOfMarsGear
  alwaysUseSpawner: true
  icon: "JobIconlegionerRecruit"
  supervisors: job-name-caesar-legion-female # changed aux and aom to have their own command chain under priestess.
  canBeAntag: false
  accessGroups:
    - CaesarLegionAcolyteOfMars
  special:
    - !type:AddComponentSpecial
      components:
        - type: BibleUser #Lets them heal with bibles
        - type: NpcFactionMember
          factions:
            - CaesarLegion
        - type: ReplacementAccent
          accent: latin
        - type: Warcry
          action: ActionLegionWarcry
          targetDepartment: CaesarLegion
          range: 6
          speedBonus: 0.30 # #Misfits Tweak - reduced from 0.50, was too strong
          duration: 10
          overlayColor: "#D64545"
          speechVerb: MisfitsLegionWarcry
          warcryMessage: warcry-message-legion
          warcryMessageCount: 6
          buffPopup: warcry-popup-buffed-legion
          excludedJobs:
          - SuperMutantGladiator
          cautionPopup: true
          activatorJobs:
          - CaesarLegionVexillarius
          - CaesarLegionDean
          - CaesarLegionPrimeDecanus
          - CaesarLegionVeteranDecanus
          - CaesarLegionCenturion
          - CaesarLegionLegate
          - CaesarLegionOptio
          - CaesarLegionPriestessOfMars
          - CaesarLegionAcolyteOfMars
        - type: CPRTraining # Taught by the POM
    - !type:AddTraitSpecial
      traits: [ LanguageLatin ]

- type: startingGear
  id: CaesarLegionAcolyteOfMarsGear
  equipment:
    wallet: N14Wallet
    jumpsuit: N14ClothingUniformJumpsuitLegionnaire
    ears: N14ClothingHeadsetLegion
    neck: N14ClothingNeckAcolyteCloak
    mask: N14ClothingMaskBrownMask
    back: N14ClothingBackpackMilitary
    shoes: N14ClothingBootsLeather
    gloves: N14ClothingHandsGlovesTribal
    outerClothing: N14ClothingOuterMarsCultRobes
    pocket1: LegionAcolyteLoadoutKits
    id: N14IDLegionaryBadge
  innerClothingSkirt: N14ClothingUniformJumpsuitLegionnaireOther
  storage:
    back:
    - N14BoxPlasticFilledMilitaryLegion
    - N14HealingPowder
    - N14HealingPowder
    - N14HealingPoultice
    - N14HealingPoultice
    - BibleMars

- type: playTimeTracker
  id: CaesarLegionAcolyteOfMars
