using Content.Client._Misfits.WastelandMap;
using Content.Client.UserInterface.Controls;
using Content.Shared._Misfits.WastelandMap;
using Robust.Client.AutoGenerated;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Utility;

namespace Content.Client._Misfits.ChalkboardOrders;

[GenerateTypedNameReferences]
public sealed partial class ChalkboardOrdersWindow : FancyWindow
{
    public event Action<WastelandMapAnnotation>? OnAddAnnotation;
    public event Action<int>? OnRemoveAnnotation;
    public event Action? OnClearAnnotations;

    private readonly MapViewerControl _mapViewer;
    private ResPath? _loadedTexturePath;

    public ChalkboardOrdersWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _mapViewer = new MapViewerControl
        {
            HorizontalExpand = true,
            VerticalExpand = true,
        };

        _mapViewer.OnAddAnnotation += annotation => OnAddAnnotation?.Invoke(annotation);
        _mapViewer.OnRemoveAnnotation += index => OnRemoveAnnotation?.Invoke(index);
        _mapViewer.OnClearAnnotations += () => OnClearAnnotations?.Invoke();
        BoardContainer.AddChild(_mapViewer);

        PanModeButton.OnPressed += _ =>
        {
            _mapViewer.SetAnnotationMode(MapViewerControl.AnnotationMode.None);
            FooterText.Text = "Pan mode: scroll to zoom and drag to move around the board";
        };

        MarkerModeButton.OnPressed += _ =>
        {
            _mapViewer.SetAnnotationMode(MapViewerControl.AnnotationMode.Marker);
            FooterText.Text = "Marker mode: left click to place a labeled order marker";
        };

        BoxModeButton.OnPressed += _ =>
        {
            _mapViewer.SetAnnotationMode(MapViewerControl.AnnotationMode.Box);
            FooterText.Text = "Box mode: drag to outline a key area for orders";
        };

        DrawModeButton.OnPressed += _ =>
        {
            _mapViewer.SetAnnotationMode(MapViewerControl.AnnotationMode.Draw);
            FooterText.Text = "Draw mode: click and drag to sketch routes, sectors, or plans";
        };

        EraseButton.OnPressed += _ =>
        {
            _mapViewer.SetAnnotationMode(MapViewerControl.AnnotationMode.Erase);
            FooterText.Text = "Erase mode: hover and left click to remove an annotation";
        };

        ClearBoardButton.OnPressed += _ => _mapViewer.ClearAnnotations();
        AnnotationText.OnTextChanged += args => _mapViewer.SetPendingAnnotationText(args.Text);
        _mapViewer.SetPendingAnnotationText(AnnotationText.Text);

        var swatches = new (Color Color, string Name)[]
        {
            (new Color(0.98f, 0.98f, 0.98f, 1f), "Chalk White"),
            (new Color(0.90f, 0.55f, 0.20f, 1f), "Orange"),
            (new Color(0.90f, 0.20f, 0.20f, 1f), "Red"),
            (new Color(0.95f, 0.90f, 0.25f, 1f), "Yellow"),
            (new Color(0.30f, 0.85f, 0.35f, 1f), "Green"),
            (new Color(0.30f, 0.65f, 0.98f, 1f), "Blue"),
        };

        ColorRow.AddChild(new Label { Text = "Color: " });
        foreach (var (swatch, name) in swatches)
        {
            var color = swatch;
            var button = new Button { Text = "Clr", ToolTip = name };
            button.ModulateSelfOverride = color;
            button.OnPressed += _ => _mapViewer.SetAnnotationColor(color);
            ColorRow.AddChild(button);
        }

        ColorRow.AddChild(new Label { Text = "  Width: " });
        foreach (var (pixels, label) in new (float, string)[] { (2f, "Thin"), (4f, "Med"), (8f, "Thick"), (12f, "Max") })
        {
            var width = pixels;
            var widthButton = new Button { Text = label };
            widthButton.OnPressed += _ => _mapViewer.SetAnnotationStrokeWidth(width);
            ColorRow.AddChild(widthButton);
        }
    }

    public void SetBoard(string title, string texturePathRaw, WastelandMapAnnotation[] sharedAnnotations)
    {
        BoardTitle.Text = title;
        Title = title;

        var texturePath = new ResPath(texturePathRaw);
        if (_loadedTexturePath != texturePath)
        {
            var resourceCache = IoCManager.Resolve<IResourceCache>();
            var fullPath = new ResPath("/Textures") / texturePath;

            if (resourceCache.TryGetResource<TextureResource>(fullPath, out var textureResource))
            {
                // Zero-sized bounds intentionally disable local-player marker rendering.
                _mapViewer.SetTexture(textureResource.Texture, new Box2(0f, 0f, 0f, 0f));
                _loadedTexturePath = texturePath;
            }
        }

        _mapViewer.SetTrackedBlips([]);
        _mapViewer.SetAnnotations(sharedAnnotations);
    }
}
