using Content.Shared._RMC.Vendors;
using Content.Client.UserInterface;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;
using System.Numerics;

namespace Content.Client._RMC.Vendors;

[GenerateTypedNameReferences]
public sealed partial class CMAutomatedVendorWindow : DefaultWindow
{
    private enum VendorPage
    {
        Allocation,
        SharedEquipment,
    }

    [Dependency] private IPrototypeManager _prototypes = default!;
    [Dependency] private IEntityManager _entities = default!;

    public event Action<int, int>? OnVend;
    public event Action? OnReplenishHeld;
    public event Action? OnStoreHeld;
    public event Action<int>? OnWithdrawStored;

    private SpriteSystem _sprites = default!;
    private VendorPage _activePage = VendorPage.Allocation;
    private string? _allocationCategory;
    private readonly Dictionary<string, bool> _allocationExpanded = new();

    public CMAutomatedVendorWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _sprites = _entities.System<SpriteSystem>();
    }

    public void UpdateState(CMAutomatedVendorState state)
    {
        Title = state.VendorTitle;
        var allocationCategories = GetCategories(
            state.AllocationCategories,
            state.Sections.SelectMany(section => section.Entries).Select(entry => entry.Category));

        _allocationCategory = EnsureCategory(_allocationCategory, allocationCategories);

        Sections.RemoveAllChildren();
        AddPageButtons(state);

        if (_activePage == VendorPage.Allocation)
        {
            AddCategoryButtons(state, allocationCategories);
            AddAllocationContent(state, _allocationCategory!);
        }
        else
            AddSharedEquipmentContent(state);
    }

    private void AddPageButtons(CMAutomatedVendorState state)
    {
        var pages = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            SeparationOverride = 6,
            Margin = new Thickness(6),
            HorizontalExpand = true,
        };

        pages.AddChild(CreateTabButton("Allocation", _activePage == VendorPage.Allocation, () =>
        {
            _activePage = VendorPage.Allocation;
            UpdateState(state);
        }));
        pages.AddChild(CreateTabButton($"{state.DepartmentName} shared equipment", _activePage == VendorPage.SharedEquipment, () =>
        {
            _activePage = VendorPage.SharedEquipment;
            UpdateState(state);
        }));
        Sections.AddChild(pages);
    }

    private void AddCategoryButtons(CMAutomatedVendorState state, IReadOnlyList<string> allocationCategories)
    {
        const int tabsPerRow = 7;
        BoxContainer? row = null;
        for (var index = 0; index < allocationCategories.Count; index++)
        {
            if (index % tabsPerRow == 0)
            {
                row = new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Horizontal,
                    SeparationOverride = 4,
                    Margin = new Thickness(6, 0, 6, 4),
                    HorizontalExpand = true,
                };
                Sections.AddChild(row);
            }

            var category = allocationCategories[index];
            var captured = category;
            row!.AddChild(CreateTabButton(category, category == _allocationCategory, () =>
            {
                _allocationCategory = captured;
                UpdateState(state);
            }));
        }
    }

    private void AddAllocationContent(CMAutomatedVendorState state, string category)
    {
        for (var sectionIndex = 0; sectionIndex < state.Sections.Count; sectionIndex++)
        {
            var section = state.Sections[sectionIndex];
            var entries = section.Entries
                .Select((entry, entryIndex) => (entry, entryIndex))
                .Where(pair => pair.entry.Category == category)
                .ToList();
            if (entries.Count == 0)
                continue;

            var entryList = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                SeparationOverride = 4,
                Margin = new Thickness(4),
                HorizontalExpand = true,
            };

            foreach (var (entry, entryIndex) in entries)
                entryList.AddChild(CreateAllocationEntry(state, section, entry, sectionIndex, entryIndex));

            var heading = new CollapsibleHeading($"{section.Name} [{entries.Count}]") { HorizontalExpand = true };
            heading.Label.HorizontalExpand = true;
            heading.Label.HorizontalAlignment = HAlignment.Left;
            var body = new CollapsibleBody { HorizontalExpand = true, Children = { entryList } };
            var collapsible = new Collapsible(heading, body)
            {
                HorizontalExpand = true,
                BodyVisible = _allocationExpanded.TryGetValue(section.Name, out var expanded) ? expanded : true,
            };
            heading.OnToggled += args => _allocationExpanded[section.Name] = args.Pressed;
            Sections.AddChild(collapsible);
        }
    }

    private Control CreateAllocationEntry(
        CMAutomatedVendorState state,
        CMVendorSectionState section,
        CMVendorEntryState entry,
        int sectionIndex,
        int entryIndex)
    {
        var text = ResolveName(entry.Name, entry.Id);
        if (entry.Amount is { } amount)
            text += $" ({amount})";
        if (entry.Points is { } points)
            text += $" [{points} pts]";
        if (!entry.HasAuthority)
            text += $" — Requires {entry.RequiredAuthority}";

        var button = new Button
        {
            Text = text,
            ToolTip = text,
            MinWidth = 260,
            MaxWidth = 360,
            TextAlign = Label.AlignMode.Left,
        };
        button.Disabled = entry.Amount is <= 0 ||
                          !entry.HasAuthority ||
                          entry.Points is { } cost && cost > state.Points ||
                          section.Choices is { } choices && section.Purchases >= choices;
        if (!entry.HasAuthority)
            button.ModulateSelfOverride = Color.OrangeRed;

        return CreateEntryRow(text, entry.Id, () => OnVend?.Invoke(sectionIndex, entryIndex), button);
    }

    private void AddSharedEquipmentContent(CMAutomatedVendorState state)
    {
        if (state.CanReplenish || state.CanStoreEquipment)
        {
            var actions = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                SeparationOverride = 4,
                Margin = new Thickness(4),
                HorizontalExpand = true,
            };

            if (state.CanReplenish)
            {
                var replenish = new Button
                {
                    Text = $"Contribute held replenishment item ({state.ReplenishmentPoints} stock points)",
                    HorizontalExpand = true,
                };
                replenish.OnPressed += _ => OnReplenishHeld?.Invoke();
                actions.AddChild(replenish);
            }

            if (state.CanStoreEquipment)
            {
                var store = new Button
                {
                    Text = $"Store your held equipment for the {state.DepartmentName}",
                    HorizontalExpand = true,
                };
                store.OnPressed += _ => OnStoreHeld?.Invoke();
                actions.AddChild(store);
            }

            Sections.AddChild(actions);
        }

        var stored = state.StoredItems.Select((item, index) => (item, index)).ToList();
        if (stored.Count == 0)
        {
            Sections.AddChild(new Label
            {
                Text = $"No shared equipment stored for the {state.DepartmentName}.",
                Margin = new Thickness(8),
            });
            return;
        }

        var entries = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            SeparationOverride = 4,
            Margin = new Thickness(4),
            HorizontalExpand = true,
        };
        foreach (var (entry, index) in stored)
            entries.AddChild(CreateEntryRow(entry.Name, entry.Id, () => OnWithdrawStored?.Invoke(index)));
        Sections.AddChild(entries);
    }

    private static List<string> GetCategories(IEnumerable<string> configured, IEnumerable<string> used)
    {
        return configured.Concat(used)
            .Where(category => !string.IsNullOrWhiteSpace(category))
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .ToList();
    }

    private static string EnsureCategory(string? selected, IReadOnlyList<string> categories)
    {
        if (selected != null && categories.Contains(selected, StringComparer.OrdinalIgnoreCase))
            return categories.First(category => category.Equals(selected, StringComparison.OrdinalIgnoreCase));

        return categories.FirstOrDefault() ?? "Other";
    }

    private static Button CreateTabButton(string text, bool selected, Action onPressed)
    {
        var button = new Button { Text = text, HorizontalExpand = true };
        if (selected)
            button.ModulateSelfOverride = Color.CornflowerBlue;
        button.OnPressed += _ => onPressed();
        return button;
    }

    private string ResolveName(string fallback, EntProtoId id)
    {
        return _prototypes.TryIndex<EntityPrototype>(id, out var prototype) ? prototype.Name : fallback;
    }

    private Control CreateEntryRow(string text, EntProtoId id, Action onPressed, Button? button = null)
    {
        var icon = default(Texture);
        if (_prototypes.TryIndex<EntityPrototype>(id, out var prototype))
            icon = _sprites.GetPrototypeIcon(prototype).Default;

        var row = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal };
        row.AddChild(new TextureRect
        {
            Texture = icon,
            SetSize = new Vector2(32, 32),
            Stretch = TextureRect.StretchMode.KeepAspectCentered,
        });

        button ??= new Button
        {
            Text = text,
            ToolTip = text,
            MinWidth = 260,
            MaxWidth = 360,
            TextAlign = Label.AlignMode.Left,
        };
        button.OnPressed += _ => onPressed();
        row.AddChild(button);
        return row;
    }
}
