using Content.Client.UserInterface.Controls;
using Content.Shared._Misfits.Vehicles.Vertibird;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Misfits.Vehicles.Vertibird;

[GenerateTypedNameReferences]
public sealed partial class VertibirdWindow : FancyWindow
{
    public event Action<int>? OnSeatSelected;
    public event Action? OnLoadCargo;
    public event Action<NetEntity>? OnUnloadCargo;

    public VertibirdWindow()
    {
        RobustXamlLoader.Load(this);

        LoadCargoButton.OnPressed += _ => OnLoadCargo?.Invoke();
    }

    public void SetState(VertibirdSeatBoundUserInterfaceState state)
    {
        Title = state.Title;

        var stateName = Loc.GetString($"vertibird-state-{state.FlightState.ToString().ToLowerInvariant()}");
        StatusLabel.Text = Loc.GetString("vertibird-window-status", ("state", stateName));
        AltitudeLabel.Text = Loc.GetString("vertibird-window-altitude", ("altitude", state.Altitude));

        var occupied = state.Seats.Count(seat => seat.OccupantName != null);
        OccupancyLabel.Text = Loc.GetString("vertibird-window-occupancy",
            ("occupied", occupied),
            ("capacity", state.Seats.Length));

        FuelBar.MaxValue = Math.Max(state.MaxFuel, 1f);
        FuelBar.Value = Math.Clamp(state.Fuel, 0f, FuelBar.MaxValue);
        FuelText.Text = Loc.GetString("vertibird-window-fuel-value",
            ("fuel", MathF.Round(state.Fuel)),
            ("max", MathF.Round(state.MaxFuel)));

        StructureBar.MaxValue = Math.Max(state.MaxStructuralIntegrity, 1f);
        StructureBar.Value = Math.Clamp(state.StructuralIntegrity, 0f, StructureBar.MaxValue);
        StructureText.Text = Loc.GetString("vertibird-window-structure-value",
            ("integrity", MathF.Round(state.StructuralIntegrity)),
            ("max", MathF.Round(state.MaxStructuralIntegrity)));

        FlightCrewList.RemoveAllChildren();
        PassengerList.RemoveAllChildren();

        foreach (var seat in state.Seats)
        {
            var list = seat.Index <= 1 ? FlightCrewList : PassengerList;
            list.AddChild(BuildSeatRow(seat, state.FlightState));
        }

        CargoLabel.Text = Loc.GetString("vertibird-window-cargo-count",
            ("stored", state.Cargo.Length),
            ("capacity", state.CargoCapacity));

        CargoList.RemoveAllChildren();
        if (state.Cargo.Length == 0)
        {
            CargoList.AddChild(new Label
            {
                Text = Loc.GetString("vertibird-cargo-empty"),
                HorizontalExpand = true,
            });
        }
        else
        {
            foreach (var crate in state.Cargo)
            {
                CargoList.AddChild(BuildCargoRow(crate));
            }
        }

        LoadCargoButton.Disabled = state.Cargo.Length >= state.CargoCapacity;
    }

    private Control BuildCargoRow(VertibirdCargoUiState crate)
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            Margin = new Thickness(0, 0, 0, 6),
        };

        row.AddChild(new Label
        {
            Text = crate.Name,
            HorizontalExpand = true,
            ClipText = true,
            VerticalAlignment = VAlignment.Center,
        });

        var button = new Button
        {
            Text = Loc.GetString("vertibird-cargo-unload"),
            MinWidth = 84,
        };

        button.OnPressed += _ => OnUnloadCargo?.Invoke(crate.Crate);

        row.AddChild(button);
        return row;
    }

    private Control BuildSeatRow(VertibirdSeatUiState seat, VertibirdFlightState flightState)
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            Margin = new Thickness(0, 0, 0, 6),
        };

        var label = new Label
        {
            Text = seat.Name,
            MinWidth = 132,
            VerticalAlignment = VAlignment.Center,
        };

        var occupant = new Label
        {
            Text = seat.OccupantName ?? Loc.GetString("vertibird-seat-empty"),
            HorizontalExpand = true,
            ClipText = true,
            VerticalAlignment = VAlignment.Center,
        };

        var button = new Button
        {
            Text = seat.OccupantName == null
                ? Loc.GetString("vertibird-seat-board")
                : Loc.GetString("vertibird-seat-occupied"),
            Disabled = seat.OccupantName != null || flightState != VertibirdFlightState.Grounded,
            MinWidth = 84,
        };

        if (seat.RequiresPilotPerk)
            button.ToolTip = Loc.GetString("vertibird-seat-requires-perk");

        button.OnPressed += _ => OnSeatSelected?.Invoke(seat.Index);

        row.AddChild(label);
        row.AddChild(occupant);
        row.AddChild(button);
        return row;
    }
}
