// #Cythisiax Add - Wendover Free Market Exchange client window
using Content.Shared._Misfits.Trade.Market;
using Robust.Client.UserInterface;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Localization;

namespace Content.Client._Misfits.Trade.Market;

[GenerateTypedNameReferences]
public sealed partial class MarketWindow : DefaultWindow
{
    public event Action<CreateOrderMessage>? OnListRequest;
    public event Action<string>? OnViewRequest;
    public event Action<string, int>? OnPurchase;
    public event Action<string>? OnClaim;
    public event Action<string>? OnCancel;
    public event Action<string>? OnProtoSearch;
    public event Action<string>? OnBarterSearch;

    private string? _selectedProtoId;
    private string? _selectedProtoName;
    private string? _selectedBarterId;
    private List<MarketItemSummary> _itemSummaries = new();

    public MarketWindow()
    {
        RobustXamlLoader.Load(this);
        Stylesheet = MarketUiStyles.Create();

        foreach (var button in new[] { ProtoSearchBtn, SubmitOrderBtn, BarterSearchBtn })
            MarketUiStyles.ApplyActionButton(button);

        TabExchangeBtn.OnPressed += _ => SwitchTab(0);
        TabCreateBtn.OnPressed += _ => SwitchTab(1);
        TabMyOrdersBtn.OnPressed += _ => SwitchTab(2);
        TabActivityBtn.OnPressed += _ => SwitchTab(3);

        foreach (var c in new[] { "Bottlecaps", "Barter" })
        {
            OrderCurrencyBtn.AddItem(c);
            OrderCurrencyBtn.SetItemMetadata(OrderCurrencyBtn.ItemCount - 1, c);
        }
        OrderCurrencyBtn.SelectId(0);
        OrderCurrencyBtn.OnItemSelected += args =>
        {
            OrderCurrencyBtn.SelectId(args.Id);
            BarterSearchBox.Visible = (string?)OrderCurrencyBtn.SelectedMetadata == "Barter";
            if (!BarterSearchBox.Visible)
                _selectedBarterId = null;
            UpdateBarterLabel();
            UpdateFeeLabel();
        };

        OrderPrice.OnTextChanged += _ => UpdateFeeLabel();
        SubmitOrderBtn.OnPressed += _ => SubmitOrder();
        ProtoSearchBtn.OnPressed += _ => ApplyMarketSearch();
        ProtoSearch.OnTextChanged += _ => ApplyMarketSearch();
        BarterSearchBtn.OnPressed += _ => OnBarterSearch?.Invoke(BarterSearch.Text.Trim());

        UpdateBarterLabel();
    }

    // #Cythisiax Add - Market title comes from the server state so the window can
    // stay aligned with future rename/config changes.
    public void SetMarketName(string title)
    {
        Title = title;
    }

    private void SwitchTab(int i)
    {
        TabExchange.Visible = i == 0; TabExchangeBtn.Disabled = i == 0;
        TabCreate.Visible = i == 1; TabCreateBtn.Disabled = i == 1;
        TabMyOrders.Visible = i == 2; TabMyOrdersBtn.Disabled = i == 2;
        TabActivity.Visible = i == 3; TabActivityBtn.Disabled = i == 3;
    }

    public void UpdateBalances(int caps, int ncr)
    {
        CapsLabel.Text = $"Caps: {caps}";
        NcrLabel.Text = $"NCR: {ncr}";
    }

    public void UpdateItemSummaries(List<MarketItemSummary> summaries)
    {
        _itemSummaries = summaries;
        ApplyMarketSearch();
    }

    private void ApplyMarketSearch()
    {
        var query = ProtoSearch.Text.Trim();
        var summaries = string.IsNullOrWhiteSpace(query)
            ? _itemSummaries
            : _itemSummaries.Where(s =>
                s.PrototypeName.Contains(query, StringComparison.OrdinalIgnoreCase) ||
                s.PrototypeId.Contains(query, StringComparison.OrdinalIgnoreCase)).ToList();

        ItemDirectory.RemoveAllChildren();
        var hdr = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, SeparationOverride = 4 };
        hdr.AddChild(new Label { Text = "Item", MinWidth = 120, HorizontalExpand = true, StyleClasses = { "LabelSubText" } });
        hdr.AddChild(new Label { Text = "Ask", MinWidth = 36, StyleClasses = { "LabelSubText" } });
        hdr.AddChild(new Label { Text = "Bid", MinWidth = 36, StyleClasses = { "LabelSubText" } });
        ItemDirectory.AddChild(hdr);

        foreach (var s in summaries)
        {
            var row = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, SeparationOverride = 4 };
            row.AddChild(new Label { Text = s.PrototypeName, MinWidth = 120, HorizontalExpand = true });
            row.AddChild(new Label { Text = s.BestAsk > 0 ? s.BestAsk.ToString() : "-", MinWidth = 36 });
            row.AddChild(new Label { Text = s.BestBid > 0 ? s.BestBid.ToString() : "-", MinWidth = 36 });
            var btn = new Button { Text = "View", MinWidth = 46 };
            MarketUiStyles.ApplyActionButton(btn);
            btn.OnPressed += _ => OnViewRequest?.Invoke(s.PrototypeId);
            row.AddChild(btn);
            ItemDirectory.AddChild(row);
        }
    }

    public void UpdateOrderBook(OrderBookEntry? book)
    {
        OrderBookContainer.RemoveAllChildren();
        DetailContainer.RemoveAllChildren();

        if (book == null)
        {
            OrderBookContainer.AddChild(new Label { Text = "No active orders for this item.", StyleClasses = { "LabelSubText" }, Margin = new Thickness(4) });
            DetailContainer.AddChild(new Label { Text = "Select an item to view order book.", StyleClasses = { "LabelSubText" }, Margin = new Thickness(4) });
            return;
        }

        DetailContainer.AddChild(new Label { Text = book.PrototypeName, StyleClasses = { "LabelHeading" } });
        DetailContainer.AddChild(new Label { Text = book.PrototypeId, StyleClasses = { "LabelSubText" } });
        DetailContainer.AddChild(new Label { Text = $"Best ask: {(book.BestAsk > 0 ? book.BestAsk.ToString() : "-")}  |  Best bid: {(book.BestBid > 0 ? book.BestBid.ToString() : "-")}  |  Spread: {(book.Spread > 0 ? book.Spread.ToString() : "-")}", StyleClasses = { "LabelSubText" } });

        OrderBookContainer.AddChild(new Label { Text = $"{book.PrototypeName} Order Book", StyleClasses = { "LabelHeading" }, Margin = new Thickness(0, 0, 0, 4) });

        var sellHeader = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, SeparationOverride = 4 };
        sellHeader.AddChild(new Label { Text = "Seller", MinWidth = 130, HorizontalExpand = true, StyleClasses = { "LabelSubText" } });
        sellHeader.AddChild(new Label { Text = "Qty", MinWidth = 40, StyleClasses = { "LabelSubText" } });
        sellHeader.AddChild(new Label { Text = "Price", MinWidth = 70, StyleClasses = { "LabelSubText" } });
        sellHeader.AddChild(new Label { Text = "Currency", MinWidth = 82, StyleClasses = { "LabelSubText" } });
        sellHeader.AddChild(new Label { Text = "Buy", MinWidth = 38, StyleClasses = { "LabelSubText" } });
        OrderBookContainer.AddChild(sellHeader);

        foreach (var o in book.SellOrders)
        {
            var row = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, SeparationOverride = 4 };
            row.AddChild(new Label { Text = o.OwnerName, MinWidth = 130, HorizontalExpand = true });
            row.AddChild(new Label { Text = (o.Quantity - o.FulfilledQty).ToString(), MinWidth = 40 });
            row.AddChild(new Label
            {
                Text = o.Currency == "Barter"
                    ? $"{o.Price}x {o.RequestedItemName ?? o.RequestedItemId ?? "item"}"
                    : o.Price.ToString(),
                MinWidth = 70,
            });
            row.AddChild(new Label { Text = o.Currency, MinWidth = 80 });
            var qty = new LineEdit { Text = "1", MinWidth = 38 };
            row.AddChild(qty);
            var buy = new Button { Text = "Buy", MinWidth = 45 };
            MarketUiStyles.ApplyActionButton(buy);
            var orderId = o.OrderId;
            buy.OnPressed += _ =>
            {
                var amount = int.TryParse(qty.Text, out var parsed) ? parsed : 1;
                OnPurchase?.Invoke(orderId, amount);
            };
            row.AddChild(buy);
            OrderBookContainer.AddChild(row);
        }

    }

    public void UpdateDepositedItems(List<MarketDepositEntry> items, Action<string>? onWithdraw)
    {
        DepositItemsContainer.RemoveAllChildren();
        if (items.Count == 0)
        {
            DepositItemsContainer.AddChild(new Label { Text = "No items in storage.", StyleClasses = { "LabelSubText" }, Margin = new Thickness(4) });
            return;
        }
        foreach (var e in items)
        {
            var row = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, SeparationOverride = 8 };
            row.AddChild(new Label { Text = $"{e.ProtoName} x{e.Quantity}" + (e.StackCount > 0 ? $" ({e.StackCount})" : ""), HorizontalExpand = true, VerticalAlignment = VAlignment.Center });

            var listBtn = new Button { Text = "List", MinWidth = 50 };
            var protoId = e.ProtoId;
            var protoName = e.ProtoName;
            listBtn.OnPressed += _ =>
            {
                _selectedProtoId = protoId;
                _selectedProtoName = protoName;
                SelectedProtoLabel.Text = $"{protoName} ({protoId})";
            };
            row.AddChild(listBtn);

            var wBtn = new Button { Text = "Take", MinWidth = 50 };
            var s = e.SlotKey;
            wBtn.OnPressed += _ => onWithdraw?.Invoke(s);
            row.AddChild(wBtn);
            DepositItemsContainer.AddChild(row);
        }
    }

    public void UpdateMyOrders(List<MarketOrder> orders, List<MarketOrder> completed)
    {
        MyOrdersContainer.RemoveAllChildren();
        if (orders.Count == 0)
            MyOrdersContainer.AddChild(new Label { Text = "No active orders.", StyleClasses = { "LabelSubText" }, Margin = new Thickness(4) });
        foreach (var o in orders)
        {
            var row = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, SeparationOverride = 8, Margin = new Thickness(0, 1) };
            var price = o.Currency == "Barter"
                ? $"{o.Price}x {o.RequestedItemName ?? o.RequestedItemId ?? "item"}/ea"
                : $"{o.Price}/ea {o.Currency}";
            row.AddChild(new Label { Text = $"SELL {o.PrototypeName} x{o.Quantity} for {price} — {o.FulfilledQty}/{o.Quantity} sold", HorizontalExpand = true });
            var cb = new Button { Text = "Cancel", MinWidth = 60 };
            var oid = o.OrderId;
            cb.OnPressed += _ => OnCancel?.Invoke(oid);
            row.AddChild(cb);
            if (o.Currency == "Barter" && o.FulfilledQty > 0)
            {
                var claim = new Button { Text = "Claim", MinWidth = 60 };
                claim.OnPressed += _ => OnClaim?.Invoke(oid);
                row.AddChild(claim);
            }
            MyOrdersContainer.AddChild(row);
        }

        MyCompletedContainer.RemoveAllChildren();
        if (completed.Count == 0)
            MyCompletedContainer.AddChild(new Label { Text = "No completed orders.", StyleClasses = { "LabelSubText" }, Margin = new Thickness(4) });
        foreach (var o in completed)
        {
            var row = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, SeparationOverride = 8, Margin = new Thickness(0, 1) };
            row.AddChild(new Label { Text = $"SELL {o.PrototypeName} x{o.Quantity} — Sold", HorizontalExpand = true });
            if (o.Currency == "Barter")
            {
                var cb = new Button { Text = "Claim", MinWidth = 60 };
                var oid = o.OrderId;
                cb.OnPressed += _ => OnClaim?.Invoke(oid);
                row.AddChild(cb);
            }
            MyCompletedContainer.AddChild(row);
        }
    }

    public void UpdateFeed(List<MarketFeedEntry> feed)
    {
        FeedContainer.RemoveAllChildren();
        if (feed.Count == 0) { FeedContainer.AddChild(new Label { Text = "No market activity yet.", StyleClasses = { "LabelSubText" }, Margin = new Thickness(4) }); return; }
        foreach (var e in feed)
            FeedContainer.AddChild(new Label { Text = $"[{e.Time.ToLocalTime():HH:mm}] {e.Text}", StyleClasses = { "LabelSubText" } });
    }

    private void UpdateFeeLabel()
    {
        var cur = (string?)OrderCurrencyBtn.SelectedMetadata;
        if (string.IsNullOrEmpty(cur) || !int.TryParse(OrderPrice.Text, out var p) || p <= 0) { OrderFeeLabel.Text = ""; return; }
        if (cur == "Barter") { OrderFeeLabel.Text = "No fee"; return; }
        OrderFeeLabel.Text = $"Fee: {p / 10} {cur}";
    }

    public void OnSearchResults(List<(string Id, string Name)> results)
    {
        BarterResultsContainer.RemoveAllChildren();
        foreach (var (id, name) in results)
        {
            var row = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, SeparationOverride = 8 };
            row.AddChild(new Label { Text = $"{name} ({id})", HorizontalExpand = true, VerticalAlignment = VAlignment.Center });
            var sel = new Button { Text = "Select", MinWidth = 50 };
            sel.OnPressed += _ =>
            {
                _selectedBarterId = id;
                UpdateBarterLabel();
            };
            row.AddChild(sel);
            BarterResultsContainer.AddChild(row);
        }
    }

    private void SubmitOrder()
    {
        var cur = (string?)OrderCurrencyBtn.SelectedMetadata ?? "Bottlecaps";
        if (!int.TryParse(OrderPrice.Text, out var price) || price <= 0)
        {
            ShowActionResult("Enter a price greater than zero.", false);
            return;
        }
        if (!int.TryParse(OrderQty.Text, out var qty) || qty <= 0)
        {
            ShowActionResult("Enter a quantity greater than zero.", false);
            return;
        }
        if (_selectedProtoId == null)
        {
            ShowActionResult("Select an item from market storage first.", false);
            return;
        }
        if (cur == "Barter" && _selectedBarterId == null)
        {
            ShowActionResult("Select the item requested in barter first.", false);
            return;
        }

        OnListRequest?.Invoke(new CreateOrderMessage(_selectedProtoId, qty, cur, price, false,
            _selectedBarterId, cur == "Barter" ? price : 0));
        ShowActionResult("Submitting listing...", true);
    }

    public void ShowActionResult(string message, bool success)
    {
        ActionResultLabel.Text = message;
        ActionResultLabel.Modulate = success ? Color.LightGreen : Color.LightCoral;
    }

    private void UpdateBarterLabel()
    {
        if (!BarterSearchBox.Visible)
        {
            SelectedBarterLabel.Text = string.Empty;
            return;
        }

        SelectedBarterLabel.Text = _selectedBarterId == null
            ? Loc.GetString("market-barter-request-none")
            : Loc.GetString("market-barter-request-selected", ("item", _selectedBarterId));
    }
}
