// #Misfits Add - Code-behind for the dedicated S.P.E.C.I.A.L. allocation window
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Systems.Character.Windows;

[GenerateTypedNameReferences]
public sealed partial class SpecialWindow : DefaultWindow
{
    public SpecialWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
