// #Misfits Change - WalletWindow superseded: Currency Wallet button in Character Menu now opens
// the full CurrencyWalletWindow via CurrencyWalletSystem.OpenWallet().
// Kept (not deleted) per project convention; this file remains as a compile-time XAML backing type.
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Systems.Character.Windows;

[GenerateTypedNameReferences]
public sealed partial class WalletWindow : DefaultWindow
{
    public WalletWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
