// #Misfits Add - Code-behind for the Group panel GUI.
// Handles member list display, pending-invite banner, leader controls visibility,
// and fires events back to GroupClientSystem.

using System;
using System.Collections.Generic;
using System.Linq;
using Content.Client.Message;
using Content.Client.UserInterface.Controls;
using Content.Shared._Misfits.Group;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Network;
using Robust.Shared.Map;

namespace Content.Client._Misfits.Group.UI;

/// <summary>
/// Group panel window. Allows players to create/manage their group,
/// invite members by character name, toggle the [ALLY] overlay, and leave/disband.
/// All validation is server-side; this window only collects input and shows feedback.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class GroupWindow : FancyWindow
{
    private readonly Dictionary<string, GroupMemberRole> _memberRoles = new(StringComparer.OrdinalIgnoreCase);
    private GroupMemberRole _roleTargetRole = GroupMemberRole.Member;

    // ── Events fired back to GroupClientSystem ─────────────────────────────

    /// <summary>Player clicked "Create Group".</summary>
    public event Action? OnCreate;

    /// <summary>Player submitted an invite. Arg: character name.</summary>
    public event Action<string>? OnInvite;

    /// <summary>Player renamed the group. Arg: new group name.</summary>
    public event Action<string>? OnRename;

    /// <summary>Player clicked the nearby-player invite helper.</summary>
    public event Action? OnInviteNearby;

    /// <summary>Player accepted the pending invite.</summary>
    public event Action? OnAcceptInvite;

    /// <summary>Player declined the pending invite.</summary>
    public event Action? OnDeclineInvite;

    /// <summary>Player clicked Leave / Disband.</summary>
    public event Action? OnLeave;

    /// <summary>Player clicked Kick. Arg: character name.</summary>
    public event Action<string>? OnKick;

    /// <summary>Player toggled a member's role. Args: character name, new role.</summary>
    public event Action<string, GroupMemberRole>? OnChangeRole;

    /// <summary>Player set the group's rally point to their current location.</summary>
    public event Action? OnSetRallyPoint;

    /// <summary>Player cleared the group's rally point.</summary>
    public event Action? OnClearRallyPoint;

    /// <summary>Player toggled the [ALLY] overlay checkbox. Arg: whether it is now enabled.</summary>
    public event Action<bool>? OnToggleOverlay;

    // ── Constructor ────────────────────────────────────────────────────────

    public GroupWindow()
    {
        RobustXamlLoader.Load(this);

        CreateGroupButton.OnPressed  += _ => OnCreate?.Invoke();
        AcceptInviteButton.OnPressed += _ => OnAcceptInvite?.Invoke();
        DeclineInviteButton.OnPressed += _ => OnDeclineInvite?.Invoke();
        LeaveButton.OnPressed        += _ => OnLeave?.Invoke();

        InviteButton.OnPressed += _ =>
        {
            var name = InviteNameEdit.Text.Trim();
            if (string.IsNullOrEmpty(name))
                return;
            OnInvite?.Invoke(name);
            InviteNameEdit.Text = string.Empty;
        };

        RenameButton.OnPressed += _ =>
        {
            var name = GroupNameEdit.Text.Trim();
            if (string.IsNullOrEmpty(name))
                return;
            OnRename?.Invoke(name);
            GroupNameEdit.Text = string.Empty;
        };

        InviteNearbyButton.OnPressed += _ => OnInviteNearby?.Invoke();

        KickButton.OnPressed += _ =>
        {
            var name = KickNameEdit.Text.Trim();
            if (string.IsNullOrEmpty(name))
                return;
            OnKick?.Invoke(name);
            KickNameEdit.Text = string.Empty;
        };

        RoleToggleButton.OnPressed += _ =>
        {
            var name = RoleNameEdit.Text.Trim();
            if (string.IsNullOrEmpty(name))
                return;

            var role = _roleTargetRole == GroupMemberRole.Member
                ? GroupMemberRole.Officer
                : GroupMemberRole.Member;
            OnChangeRole?.Invoke(name, role);
        };

        SetRallyButton.OnPressed += _ => OnSetRallyPoint?.Invoke();
        ClearRallyButton.OnPressed += _ => OnClearRallyPoint?.Invoke();

        OverlayToggle.OnToggled += args => OnToggleOverlay?.Invoke(args.Pressed);
        RoleNameEdit.OnTextChanged += _ => UpdateRoleToggleText();

        // Default hide invite and leader controls; UpdateState will show them.
        InvitePanel.Visible    = false;
        InviteDivider.Visible  = false;
        LeaderControls.Visible = false;
        LeaveButton.Visible    = false;
        CreateGroupButton.Visible = true;
    }

    // ── Public API called by GroupClientSystem ─────────────────────────────

    /// <summary>
    /// Refresh window state whenever a <see cref="GroupStateUpdateEvent"/> arrives
    /// or the window is first opened.
    /// </summary>
    /// <param name="members">List of (entity, display name) pairs for all group members.</param>
    /// <param name="leaderUserId">UserId of the current group leader, or null if not in a group.</param>
    /// <param name="myUserId">The local player's UserId.</param>
    /// <param name="pendingInviteFromName">Character name of who is inviting, or null if none.</param>
    public void UpdateState(
        IReadOnlyList<GroupMemberInfo> members,
        NetUserId?  leaderUserId,
        NetUserId?  myUserId,
        NetEntity?  myEntity,
        string?     groupName,
        string?     pendingInviteFromName,
        MapCoordinates? rallyPoint)
    {
        var inGroup = members.Count > 0;
        _memberRoles.Clear();
        foreach (var member in members)
            _memberRoles[member.Name] = member.Role;

        var myRole = GroupMemberRole.Member;
        if (myEntity.HasValue)
        {
            var localMember = members.FirstOrDefault(member => member.Entity == myEntity.Value);
            if (localMember != default)
                myRole = localMember.Role;
        }

        if (leaderUserId.HasValue && myUserId.HasValue && leaderUserId.Value == myUserId.Value)
            myRole = GroupMemberRole.Leader;

        var isLeader = myRole == GroupMemberRole.Leader;
        var canInvite = myRole is GroupMemberRole.Leader or GroupMemberRole.Officer;
        var canSetRallyPoint = canInvite;
        var canManageRoles = isLeader;
        var canKick = isLeader;

        // ── Pending invite banner ─────────────────────────────────────────
        var hasPendingInvite = !string.IsNullOrEmpty(pendingInviteFromName);
        InvitePanel.Visible   = hasPendingInvite;
        InviteDivider.Visible = hasPendingInvite;
        if (hasPendingInvite)
            InviteLabel.Text = Loc.GetString("group-invite-pending-label", ("name", pendingInviteFromName!));

        // ── Member list ───────────────────────────────────────────────────
        MembersContainer.RemoveAllChildren();
        if (!inGroup)
        {
            var noGroup = new Label
            {
                Text             = Loc.GetString("group-no-members-label"),
                FontColorOverride = Color.Gray,
                Margin            = new Thickness(4, 2),
            };
            MembersContainer.AddChild(noGroup);
        }
        else
        {
            foreach (var member in members)
            {
                var row = new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Horizontal,
                    HorizontalExpand = true,
                    SeparationOverride = 8,
                    Margin = new Thickness(4, 2),
                };

                var roleColor = member.Role switch
                {
                    GroupMemberRole.Leader => new Color(0.1f, 0.85f, 0.85f),
                    GroupMemberRole.Officer => new Color(0.97f, 0.78f, 0.18f),
                    _ => Color.LightGray,
                };

                row.AddChild(new Label
                {
                    Text = member.Name,
                    ClipText = true,
                    HorizontalExpand = true,
                    FontColorOverride = roleColor,
                });

                row.AddChild(new Label
                {
                    Text = GetRoleLabel(member.Role),
                    FontColorOverride = roleColor,
                    MinWidth = 72,
                    HorizontalAlignment = HAlignment.Right,
                });

                MembersContainer.AddChild(row);
            }
        }

        // ── Create button — visible only when NOT in group ────────────────
        CreateGroupButton.Visible = !inGroup;
        GroupNameLabel.Visible = inGroup;
        GroupNameLabel.Text = inGroup && !string.IsNullOrWhiteSpace(groupName)
            ? groupName
            : string.Empty;

        // ── Role-gated controls ───────────────────────────────────────────
        LeaderControls.Visible = inGroup && (canInvite || canManageRoles || canKick || canSetRallyPoint);
        RenameSection.Visible = inGroup && canManageRoles;
        InviteSection.Visible = inGroup && canInvite;
        RoleSection.Visible = inGroup && canManageRoles;
        KickSection.Visible = inGroup && canKick;
        RallySection.Visible = inGroup && canSetRallyPoint;

        // ── Leave / Disband ───────────────────────────────────────────────
        LeaveButton.Visible = inGroup;
        LeaveButton.Text = isLeader
            ? Loc.GetString("group-disband-button")
            : Loc.GetString("group-leave-button");

        Title = inGroup && !string.IsNullOrWhiteSpace(groupName)
            ? $"{Loc.GetString("group-window-title")} - {groupName}"
            : Loc.GetString("group-window-title");

        if (RenameSection.Visible)
        {
            GroupNameEdit.PlaceHolder = groupName ?? Loc.GetString("group-rename-placeholder");
            if (string.IsNullOrWhiteSpace(GroupNameEdit.Text))
                GroupNameEdit.Text = groupName ?? string.Empty;
        }

        RallyPointLabel.Text = rallyPoint.HasValue
            ? Loc.GetString("group-rally-point-active")
            : Loc.GetString("group-rally-point-none");

        InviteHintLabel.Text = canInvite
            ? Loc.GetString("group-invite-hint")
            : string.Empty;

        UpdateRoleToggleText();
        StatusLabel.SetMessage(string.Empty);
    }

    /// <summary>Show a one-line feedback message (success = green, failure = red).</summary>
    public void ShowResult(bool success, string message)
    {
        var color = success ? "#55FF55" : "#FF6644";
        StatusLabel.SetMarkup($"[color={color}]{message}[/color]");
    }

    private void UpdateRoleToggleText()
    {
        var name = RoleNameEdit.Text.Trim();
        if (string.IsNullOrWhiteSpace(name))
        {
            RoleToggleButton.Text = Loc.GetString("group-role-toggle-button");
            RoleToggleButton.Disabled = true;
            return;
        }

        if (!_memberRoles.TryGetValue(name, out var role))
        {
            RoleToggleButton.Text = Loc.GetString("group-role-toggle-button");
            RoleToggleButton.Disabled = true;
            _roleTargetRole = GroupMemberRole.Member;
            return;
        }

        if (role == GroupMemberRole.Leader)
        {
            RoleToggleButton.Text = Loc.GetString("group-role-leader-lock");
            RoleToggleButton.Disabled = true;
            _roleTargetRole = GroupMemberRole.Leader;
            return;
        }

        _roleTargetRole = role;
        RoleToggleButton.Disabled = false;
        RoleToggleButton.Text = role == GroupMemberRole.Officer
            ? Loc.GetString("group-role-demote-button")
            : Loc.GetString("group-role-promote-button");
    }

    private static string GetRoleLabel(GroupMemberRole role)
    {
        return role switch
        {
            GroupMemberRole.Leader => "[LEADER]",
            GroupMemberRole.Officer => "[OFFICER]",
            _ => "[MEMBER]",
        };
    }
}
