using Content.Shared._Misfits.MaterialExtractor;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Misfits.MaterialExtractor;

[GenerateTypedNameReferences]
public sealed partial class MaterialExtractorWindow : FancyWindow
{
    public event Action? OnStart;
    public event Action? OnStop;
    public event Action? OnEjectFuel;

    public MaterialExtractorWindow()
    {
        RobustXamlLoader.Load(this);
        StartButton.OnPressed += _ => OnStart?.Invoke();
        StopButton.OnPressed += _ => OnStop?.Invoke();
        EjectButton.OnPressed += _ => OnEjectFuel?.Invoke();
    }

    public void Update(MaterialExtractorUiState state)
    {
        StatusLabel.Text = state.Running ? "Running" : "Stopped";
        StatusLabel.SetOnlyStyleClass(state.Running ? "Good" : "Danger");
        DetailLabel.Text = state.Unattended
            ? "Requires an operator within 4 tiles"
            : state.FuelDepleted ? "Fuel depleted" : "Ready to extract materials";
        FuelBar.Value = state.FuelCapacity > 0 ? state.Fuel / state.FuelCapacity : 0;
        FuelLabel.Text = $"Fuel: {(int) MathF.Floor(state.Fuel)}";
        StartButton.Visible = !state.Running;
        StopButton.Visible = state.Running;
    }
}
