using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Client._Misfits.BrotherhoodOfSteel;

[GenerateTypedNameReferences]
public sealed partial class BosRecruitWindow : DefaultWindow
{
    // Brotherhood of Steel palette (department blue #3B72BF)
    private static readonly Color BackgroundColor = Color.FromHex("#0b0e14");
    private static readonly Color DocumentColor = Color.FromHex("#101826");
    private static readonly Color BrotherhoodBlue = Color.FromHex("#3B72BF");
    private static readonly Color SoftBlue = Color.FromHex("#7fa8dd");
    private static readonly Color BorderColor = Color.FromHex("#2a4370");
    private static readonly Color WarningAmber = Color.FromHex("#d6b85a");

    public event Action? OnAccepted;
    public event Action? OnDeclined;

    private string _recruiterName = string.Empty;
    private string _targetName = string.Empty;

    public BosRecruitWindow()
    {
        RobustXamlLoader.Load(this);

        ScreenPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = BackgroundColor,
            BorderColor = BrotherhoodBlue,
            BorderThickness = new Thickness(2),
        };
        DocumentPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = DocumentColor,
            BorderColor = BorderColor,
            BorderThickness = new Thickness(1),
        };

        TerminalHeader.SetMessage(
            "BROTHERHOOD OF STEEL // FIELD RITE // MEMORIAM: FOUNDER V. PLUM\n" +
            "AD VIKTORIYA // BY THE WILL OF THE FOUNDER",
            BrotherhoodBlue);

        PageTitle.Text = "AD VIKTORIYA";
        PageTitle.FontColorOverride = BrotherhoodBlue;
        StatusLabel.FontColorOverride = WarningAmber;

        AcceptButton.OnPressed += _ => OnAccepted?.Invoke();
        DeclineButton.OnPressed += _ => OnDeclined?.Invoke();
    }

    public void SetNames(string recruiterName, string targetName)
    {
        _recruiterName = recruiterName;
        _targetName = targetName;

        DocumentText.SetMessage(
            Loc.GetString("bos-recruit-body-text", ("recruiter", _recruiterName), ("target", _targetName)),
            SoftBlue);

        StatusLabel.Text = Loc.GetString("bos-recruit-status-text");
    }
}
