using Content.Shared.Fax;
using Robust.Client.AutoGenerated;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.RichText;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.ContentPack;
using Robust.Shared.Utility;

namespace Content.Client.Fax.AdminUI;

[GenerateTypedNameReferences]
public sealed partial class AdminFaxWindow : DefaultWindow
{
    // #Misfits Fix - Must match the in-world paper sprite states to avoid red ERROR overlays on stamped fax papers.
    private const string StampsRsiPath = "/Textures/_Nuclear14/Objects/Misc/clutter.rsi";

    private readonly List<AdminFaxInboxEntry> _inboxEntries = new();
    private bool _inboxVisible;

    public Action<(NetEntity entity, string title, string stampedBy, string message, string stampSprite, Color stampColor)>? OnMessageSend;
    public Action<NetEntity>? OnFollowFax;

    [Dependency] private readonly IResourceCache _resCache = default!;

    public AdminFaxWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        PopulateStamps();

        FaxSelector.OnItemSelected += args => FaxSelector.SelectId(args.Id);
        InboxSelector.OnItemSelected += OnInboxSelected;
        StampSelector.OnItemSelected += args => StampSelector.SelectId(args.Id);
        FollowButton.OnPressed += FollowFax;
        ToggleInboxButton.OnPressed += ToggleInbox;
        SendButton.OnPressed += SendMessage;

        // Don't use this, but ColorSelectorSliders requires it:
        // what the fok
        StampColorSelector.OnColorChanged += (color) => {};

        var loc = IoCManager.Resolve<ILocalizationManager>();
        MessageEdit.Placeholder = new Rope.Leaf(loc.GetString("admin-fax-message-placeholder")); // TextEdit work only with Nodes
    }

    public void PopulateFaxes(List<AdminFaxEntry> faxes)
    {
        FaxSelector.Clear();
        for (var i = 0; i < faxes.Count; i++)
        {
            var fax = faxes[i];
            FaxSelector.AddItem($"{fax.Name} ({fax.Address})", i);
            FaxSelector.SetItemMetadata(i, fax.Uid);
        }
    }

    public void PopulateInbox(List<AdminFaxInboxEntry> inboxEntries)
    {
        _inboxEntries.Clear();
        _inboxEntries.AddRange(inboxEntries);

        InboxSelector.Clear();

        if (_inboxEntries.Count == 0)
        {
            RenderInboxEmpty();
            return;
        }

        for (var i = 0; i < _inboxEntries.Count; i++)
        {
            var entry = _inboxEntries[i];
            InboxSelector.AddItem($"{entry.SourceFaxName} -> {entry.DestinationFaxName}: {entry.PaperTitle}", i);
            InboxSelector.SetItemMetadata(i, i);
        }

        InboxSelector.SelectId(_inboxEntries.Count - 1);
        RenderInboxPreview(_inboxEntries.Count - 1);
    }

    private void PopulateStamps()
    {
        var rsi = _resCache.GetResource<RSIResource>(StampsRsiPath).RSI;
        using (var enumerator = rsi.GetEnumerator())
        {
            var i = 0;
            while (enumerator.MoveNext())
            {
                var state = enumerator.Current;
                var stateName = state.StateId.Name!;
                if (!stateName.StartsWith("paper_stamp-"))
                    continue;

                StampSelector.AddItem(stateName, i);
                StampSelector.SetItemMetadata(i, stateName);
                i++;
            }
        }

        if (StampSelector.ItemCount > 0)
            StampSelector.SelectId(0);
    }

    private void ToggleInbox(BaseButton.ButtonEventArgs obj)
    {
        _inboxVisible = !_inboxVisible;
        InboxPanel.Visible = _inboxVisible;
        ToggleInboxButton.Text = Loc.GetString(_inboxVisible
            ? "admin-fax-inbox-toggle-hide"
            : "admin-fax-inbox-toggle-show");
    }

    private void OnInboxSelected(OptionButton.ItemSelectedEventArgs args)
    {
        InboxSelector.SelectId(args.Id);
        RenderInboxPreview(args.Id);
    }

    private void RenderInboxEmpty()
    {
        var msg = new FormattedMessage();
        msg.AddText(Loc.GetString("admin-fax-inbox-empty"));
        InboxPaperPreview.SetMessage(msg);
    }

    private void RenderInboxPreview(int index)
    {
        if (index < 0 || index >= _inboxEntries.Count)
        {
            RenderInboxEmpty();
            return;
        }

        var entry = _inboxEntries[index];
        var msg = new FormattedMessage();
        msg.AddText($"From Fax: {entry.SourceFaxName}\n");
        msg.AddText($"To Fax: {entry.DestinationFaxName}\n");
        msg.AddText($"Sender: {entry.SenderName}\n");
        msg.AddText($"Title: {entry.PaperTitle}\n\n");
        msg.AddMarkupPermissive(entry.Content);
        InboxPaperPreview.SetMessage(msg);
    }

    private void FollowFax(BaseButton.ButtonEventArgs obj)
    {
        var faxEntity = (NetEntity?) FaxSelector.SelectedMetadata;
        if (faxEntity == null)
            return;

        OnFollowFax?.Invoke(faxEntity.Value);
    }

    private void SendMessage(BaseButton.ButtonEventArgs obj)
    {
        var faxEntity = (NetEntity?) FaxSelector.SelectedMetadata;
        if (faxEntity == null)
            return;

        var stamp = (string?) StampSelector.SelectedMetadata;
        if (stamp == null)
            return;

        var title = TitleEdit.Text;
        if (string.IsNullOrEmpty(title))
            return;

        var message = Rope.Collapse(MessageEdit.TextRope);
        if (string.IsNullOrEmpty(message))
            return;

        var from = FromEdit.Text;
        var stampColor = StampColorSelector.Color;
        OnMessageSend?.Invoke((faxEntity.Value, title, from, message, stamp, stampColor));
    }
}
