// #Misfits Refactor - Player-war panel window.
// Collects client input for declare/ceasefire actions and renders server-supplied player-war state.

using Content.Client.Message;
using Content.Client.UserInterface.Controls;
using Content.Shared._Misfits.FactionWar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Network;
using Robust.Shared.Utility;

namespace Content.Client._Misfits.FactionWar.UI;

/// <summary>
/// Faction War panel window. Allows eligible players to declare war on,
/// or declare a ceasefire with, another faction.
/// All game-logic validation is done server-side; this window only collects input
/// and displays feedback from <see cref="FactionWarClientSystem"/>.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class FactionWarWindow : FancyWindow
{
    public event Action<WarTargetKind, string, string, string>? OnDeclareWar;
    public event Action<NetUserId>? OnCeasefire;
    public event Action<NetUserId>? OnAcceptCeasefireProposal;
    public event Action<NetUserId>? OnRejectCeasefireProposal;

    // ── Internal state ─────────────────────────────────────────────────────

    private readonly List<WarTargetInfo> _factionTargetItems = new();
    private readonly List<WarTargetInfo> _groupTargetItems = new();
    private readonly List<WarTargetInfo> _wastelanderTargetItems = new();
    private readonly List<PlayerWarEntry> _myWars = new();

    private bool _confirmPending;
    private WarTargetKind _selectedTargetKind = WarTargetKind.Faction;
    private NetUserId? _pendingCeasefireFrom;
    private NetUserId? _localUserId;
    private string _localCharacterName = string.Empty;

    // ── Constructor ────────────────────────────────────────────────────────

    public FactionWarWindow()
    {
        RobustXamlLoader.Load(this);

        // Keep compact static guidance in the header block.
        RulesLabel.SetMarkup(
            "[bold]Player War Rules[/bold]\n" +
            "[bullet]Pick a target faction, group, or wastelander and provide a clear reason (5+ words).[/bullet]\n" +
            "[bullet]War starts after prep and players can join a side while pending.[/bullet]\n" +
            "[bullet]Use ceasefire to end hostilities cleanly.[/bullet]");

        DeclareWarButton.OnPressed += _ => OnDeclareWarPressed();
        CeasefireButton.OnPressed += _ => SubmitCeasefire();

        AcceptCeasefireProposalButton.OnPressed += _ => SubmitAcceptCeasefireProposal();
        RejectCeasefireProposalButton.OnPressed += _ => SubmitRejectCeasefireProposal();

        // Commit dropdown selection and reset confirm state when the target changes.
        TargetFactionSelector.OnItemSelected += args =>
        {
            TargetFactionSelector.SelectId(args.Id);
            _selectedTargetKind = WarTargetKind.Faction;
            ResetConfirm();
        };
        TargetGroupSelector.OnItemSelected += args =>
        {
            TargetGroupSelector.SelectId(args.Id);
            _selectedTargetKind = WarTargetKind.Group;
            ResetConfirm();
        };
        TargetWastelanderSelector.OnItemSelected += args =>
        {
            TargetWastelanderSelector.SelectId(args.Id);
            _selectedTargetKind = WarTargetKind.Wastelander;
            ResetConfirm();
        };
        CeasefireTargetSelector.OnItemSelected += args => CeasefireTargetSelector.SelectId(args.Id);
    }

    // ── Public API called by FactionWarClientSystem ────────────────────────

    public void UpdateState(
        PlayerWarPanelDataEvent data,
        NetUserId? localUserId,
        CeasefireProposalEvent? pendingCeasefire)
    {
        _localUserId = localUserId;
        _localCharacterName = data.MyCharacterName ?? string.Empty;

        ActiveWarsContainer.RemoveAllChildren();
        if (data.ActiveWars.Count == 0)
        {
            var noWars = new Label
            {
                Text = Loc.GetString("faction-war-no-active-wars"),
                FontColorOverride = Color.Gray,
                Margin = new Thickness(4, 2),
            };
            ActiveWarsContainer.AddChild(noWars);
        }
        else
        {
            foreach (var war in data.ActiveWars)
            {
                var phaseTag = war.Phase == WarPhase.Pending ? "[PENDING] " : "";
                var entry = new Label
                {
                    Text = $"{phaseTag}{war.SideName1} vs {war.SideName2} - \"{war.Reason}\"",
                    Margin = new Thickness(4, 2),
                    ClipText = true,
                    HorizontalExpand = true,
                };
                ActiveWarsContainer.AddChild(entry);
            }
        }

        _factionTargetItems.Clear();
        _groupTargetItems.Clear();
        _wastelanderTargetItems.Clear();

        TargetFactionSelector.Clear();
        TargetGroupSelector.Clear();
        TargetWastelanderSelector.Clear();

        foreach (var target in data.FactionTargets)
        {
            _factionTargetItems.Add(target);
            TargetFactionSelector.AddItem(target.DisplayName);
        }

        foreach (var target in data.GroupTargets)
        {
            _groupTargetItems.Add(target);
            TargetGroupSelector.AddItem(target.DisplayName);
        }

        foreach (var target in data.WastelanderTargets)
        {
            _wastelanderTargetItems.Add(target);
            TargetWastelanderSelector.AddItem(target.DisplayName);
        }

        TargetFactionSelector.Disabled = _factionTargetItems.Count == 0;
        TargetGroupSelector.Disabled = _groupTargetItems.Count == 0;
        TargetWastelanderSelector.Disabled = _wastelanderTargetItems.Count == 0;

        if (_factionTargetItems.Count > 0)
        {
            _selectedTargetKind = WarTargetKind.Faction;
            TargetFactionSelector.SelectId(0);
        }
        else if (_groupTargetItems.Count > 0)
        {
            _selectedTargetKind = WarTargetKind.Group;
            TargetGroupSelector.SelectId(0);
        }
        else if (_wastelanderTargetItems.Count > 0)
        {
            _selectedTargetKind = WarTargetKind.Wastelander;
            TargetWastelanderSelector.SelectId(0);
        }
        else
        {
            _selectedTargetKind = WarTargetKind.Faction;
        }

        DeclareWarButton.Disabled = _factionTargetItems.Count == 0
                                   && _groupTargetItems.Count == 0
                                   && _wastelanderTargetItems.Count == 0;
        ResetConfirm();

        _myWars.Clear();
        _myWars.AddRange(data.MyWars);
        CeasefireTargetSelector.Clear();

        foreach (var war in _myWars)
        {
            var label = war.DeclaredByCharacterName;
            if (_localUserId != null && war.DeclaredByPlayer == _localUserId)
                label = war.DeclaredAgainstCharacterName;
            CeasefireTargetSelector.AddItem(label);
        }

        CeasefireButton.Disabled = _myWars.Count == 0;

        _pendingCeasefireFrom = pendingCeasefire?.ProposingPlayer;
        IncomingCeasefireProposalSection.Visible = pendingCeasefire != null;
        if (pendingCeasefire != null)
        {
            IncomingCeasefireProposalLabel.Text = $"{pendingCeasefire.ProposingPlayerName} proposes a ceasefire.";
            IncomingCeasefireProposerLabel.Text = "Accept or reject in this panel.";
        }

        ClearResult();
    }

    /// <summary>Display a success or error message in the result label (supports wrapping).</summary>
    public void ShowResult(bool success, string message)
    {
        var color = success ? "#32CD32" : "#FF4500";
        ResultLabel.SetMarkup($"[color={color}]{FormattedMessage.EscapeText(message)}[/color]");
    }

    // ── Private helpers ────────────────────────────────────────────────────

    /// <summary>
    /// First press: validate and switch to confirm state. Second press: fire the event.
    /// </summary>
    private void OnDeclareWarPressed()
    {
        if (DeclareWarButton.Disabled)
            return;

        var (kind, targetId) = GetSelectedTarget();
        if (targetId == null)
            return;

        var reason = CasusBelliEdit.Text.Trim();

        if (reason.Split(' ', StringSplitOptions.RemoveEmptyEntries).Length < 5)
        {
            ShowResult(false, Loc.GetString("faction-war-casus-belli-too-short"));
            return;
        }

        if (!_confirmPending)
        {
            _confirmPending = true;
            DeclareWarButton.Text = Loc.GetString("faction-war-confirm-button");
            DeclareWarButton.Modulate = Color.OrangeRed;
            ShowResult(false, Loc.GetString("faction-war-confirm-prompt"));
            return;
        }

        var sideName = string.IsNullOrWhiteSpace(_localCharacterName)
            ? "Side 1"
            : $"{_localCharacterName}'s Side";
        OnDeclareWar?.Invoke(kind, targetId, reason, sideName);
        ResetConfirm();
    }

    private (WarTargetKind Kind, string? TargetId) GetSelectedTarget()
    {
        return _selectedTargetKind switch
        {
            WarTargetKind.Faction => GetTargetId(TargetFactionSelector, _factionTargetItems),
            WarTargetKind.Group => GetTargetId(TargetGroupSelector, _groupTargetItems),
            WarTargetKind.Wastelander => GetTargetId(TargetWastelanderSelector, _wastelanderTargetItems),
            _ => (WarTargetKind.Faction, null),
        };
    }

    private static (WarTargetKind Kind, string? TargetId) GetTargetId(
        OptionButton selector,
        IReadOnlyList<WarTargetInfo> items)
    {
        var idx = selector.SelectedId;
        if (idx < 0 || idx >= items.Count)
            return (WarTargetKind.Faction, null);

        return (items[idx].Kind, items[idx].Id);
    }

    private void ResetConfirm()
    {
        _confirmPending = false;
        DeclareWarButton.Text = Loc.GetString("faction-war-declare-button");
        DeclareWarButton.Modulate = Color.White;
    }

    private void SubmitCeasefire()
    {
        if (CeasefireTargetSelector.ItemCount == 0)
            return;

        var idx = CeasefireTargetSelector.SelectedId;
        if (idx < 0 || idx >= _myWars.Count || _localUserId == null)
            return;

        var war = _myWars[idx];
        var other = war.DeclaredByPlayer == _localUserId ? war.DeclaredAgainstPlayer : war.DeclaredByPlayer;
        OnCeasefire?.Invoke(other);
    }

    private void ClearResult()
    {
        ResultLabel.SetMarkup(string.Empty);
    }

    private void SubmitAcceptCeasefireProposal()
    {
        if (_pendingCeasefireFrom == null)
            return;
        OnAcceptCeasefireProposal?.Invoke(_pendingCeasefireFrom.Value);
    }

    private void SubmitRejectCeasefireProposal()
    {
        if (_pendingCeasefireFrom == null)
            return;
        OnRejectCeasefireProposal?.Invoke(_pendingCeasefireFrom.Value);
    }
}
