// #Misfits Add - Code-behind for the graffiti spray can picker window.
// Populates a list of all graffiti-tagged decals with their icons for player selection.

using System.Linq;
using Content.Shared.Decals;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Misfits.GraffitiSprayCan.UI;

[GenerateTypedNameReferences]
public sealed partial class GraffitiSprayCanWindow : DefaultWindow
{
    /// <summary>
    /// Invoked when the player selects a decal. Passes the decal prototype ID.
    /// </summary>
    public Action<string>? OnDecalPicked;

    // Parallel list to DecalList items — tracks the prototype ID at each index
    private readonly List<string> _decalIds = new();

    [Dependency] private readonly IEntitySystemManager _sysMan = default!;
    private readonly SpriteSystem _spriteSystem;

    public GraffitiSprayCanWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _spriteSystem = _sysMan.GetEntitySystem<SpriteSystem>();

        DecalList.OnItemSelected += args =>
        {
            if (args.ItemIndex >= 0 && args.ItemIndex < _decalIds.Count)
                OnDecalPicked?.Invoke(_decalIds[args.ItemIndex]);
        };
    }

    /// <summary>
    /// Fills the list with all graffiti-tagged decals. Highlights the currently selected one.
    /// </summary>
    public void Populate(IEnumerable<DecalPrototype> allDecals, string? selectedId, int charges)
    {
        _decalIds.Clear();
        DecalList.Clear();

        ChargesLabel.Text = Loc.GetString("graffiti-spray-can-charges-label", ("charges", charges));

        // Only show decals tagged "graffiti", sorted alphabetically by ID
        foreach (var decal in allDecals.Where(d => d.Tags.Contains("graffiti")).OrderBy(d => d.ID))
        {
            _decalIds.Add(decal.ID);

            // Use the decal's own sprite as the list icon
            var texture = _spriteSystem.Frame0(decal.Sprite);
            var item = DecalList.AddItem(decal.ID, texture);

            // Highlight whichever is already active
            if (decal.ID == selectedId)
                item.Selected = true;
        }
    }
}
