using Content.Client.UserInterface.Controls;
using Content.Shared.DeltaV.MedicalRecords; // #Misfits Change
using Content.Shared._Shitmed.Targeting;
using Content.Shared.MedicalScanner;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.HealthAnalyzer.UI
{
    // #Misfits Change
    /// <summary>
    /// popup shell around <see cref="HealthAnalyzerPanel"/>, which holds the actual scan display
    /// </summary>
    [GenerateTypedNameReferences]
    public sealed partial class HealthAnalyzerWindow : FancyWindow
    {
        public event Action<TargetBodyPart?, EntityUid>? OnBodyPartSelected
        {
            add => Panel.OnBodyPartSelected += value;
            remove => Panel.OnBodyPartSelected -= value;
        }

        public event Action<TriageStatus>? OnTriageStatusChanged
        {
            add => Panel.OnTriageStatusChanged += value;
            remove => Panel.OnTriageStatusChanged -= value;
        }

        public event Action? OnClaimPatient
        {
            add => Panel.OnClaimPatient += value;
            remove => Panel.OnClaimPatient -= value;
        }

        public HealthAnalyzerWindow()
        {
            RobustXamlLoader.Load(this);
        }

        public void Populate(HealthAnalyzerScannedUserMessage msg) => Panel.Populate(msg);
    }
}
