using Content.Client.UserInterface.Controls;
using Content.Shared._Misfits.Expeditions;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._Misfits.Expeditions;

/// <summary>
/// Expedition board window — lets the player pick a difficulty tier and launch.
/// Updates in real-time to show countdown/timer/cooldown status.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class N14ExpeditionBoardWindow : FancyWindow
{
    [Dependency] private readonly IGameTiming _timing = default!;

    /// <summary>Fires when the player clicks the Launch button with a chosen difficulty.</summary>
    public event Action<string>? OnLaunchExpedition;

    private string? _selectedTierId;
    private N14ExpeditionBoardState? _lastState;
    // Reference to the currently open confirm window (if any). #Misfits Change
    private N14ExpeditionConfirmWindow? _confirmWindow;

    public N14ExpeditionBoardWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        // Launch button opens the dedicated confirm window instead of an inline overlay
        LaunchButton.OnPressed += _ =>
        {
            if (_selectedTierId != null)
                ShowConfirmation();
        };
    }

    /// <summary>
    /// Called by the BUI handler whenever the server pushes new state.
    /// Rebuilds the tier buttons and updates status displays.
    /// </summary>
    public void UpdateState(N14ExpeditionBoardState state)
    {
        _lastState = state;

        // Rebuild tier buttons
        TierGrid.RemoveAllChildren();
        foreach (var tier in state.Tiers)
        {
            var button = new Button
            {
                Text = tier.Name,
                HorizontalExpand = true,  // #Misfits Fix - Fill full width in vertical stack
                MinHeight = 50,
            };
            button.ModulateSelfOverride = tier.Color;

            // Closure capture
            var tierId = tier.TierId;
            var tierName = tier.Name;
            var mapCount = tier.MapCount;
            var duration = tier.DurationMinutes;

            button.OnPressed += _ => SelectTier(tierId, tierName, mapCount, duration);
            TierGrid.AddChild(button);
        }

        // Determine overall status and button state
        if (state.ExpeditionActive)
        {
            StatusLabel.Text = Loc.GetString("n14-expedition-status-active");
            LaunchButton.Disabled = true;
            LaunchButton.Text = Loc.GetString("n14-expedition-launch-button-active");
            TimerPanel.Visible = true;
        }
        else if (state.LaunchEndTime != null)
        {
            StatusLabel.Text = Loc.GetString("n14-expedition-status-countdown");
            LaunchButton.Disabled = true;
            LaunchButton.Text = Loc.GetString("n14-expedition-status-countdown");
            TimerPanel.Visible = true;
        }
        else if (state.OnCooldown)
        {
            StatusLabel.Text = Loc.GetString("n14-expedition-status-cooldown-label");
            LaunchButton.Disabled = true;
            LaunchButton.Text = Loc.GetString("n14-expedition-launch-button");
            TimerPanel.Visible = true;
        }
        else
        {
            StatusLabel.Text = Loc.GetString("n14-expedition-select-tier");
            LaunchButton.Disabled = _selectedTierId == null;
            LaunchButton.Text = Loc.GetString("n14-expedition-launch-button");
            TimerPanel.Visible = false;
        }

        UpdateTimerDisplay();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        UpdateTimerDisplay();
    }

    private void SelectTier(string tierId, string name, int mapCount, float durationMinutes)
    {
        _selectedTierId = tierId;

        DetailsPanel.Visible = true;
        SelectedTierLabel.Text = name;
        MapCountLabel.Text = Loc.GetString("n14-expedition-maps-available", ("count", mapCount));
        DurationLabel.Text = Loc.GetString("n14-expedition-duration", ("minutes", (int) durationMinutes));

        // Enable launch only if board is idle
        if (_lastState is { ExpeditionActive: false, OnCooldown: false, LaunchEndTime: null })
        {
            LaunchButton.Disabled = false;
        }
    }

    private void UpdateTimerDisplay()
    {
        if (_lastState == null)
            return;

        var now = _timing.CurTime;

        if (_lastState.ExpeditionActive && _lastState.ExpeditionEndTime != null)
        {
            var remaining = _lastState.ExpeditionEndTime.Value - now;
            if (remaining < TimeSpan.Zero)
                remaining = TimeSpan.Zero;

            TimerLabel.Text = Loc.GetString("n14-expedition-timer-expedition",
                ("time", $"{remaining.Minutes:D2}:{remaining.Seconds:D2}"));
        }
        else if (_lastState.LaunchEndTime != null)
        {
            var remaining = _lastState.LaunchEndTime.Value - now;
            if (remaining < TimeSpan.Zero)
                remaining = TimeSpan.Zero;

            TimerLabel.Text = Loc.GetString("n14-expedition-timer-launch",
                ("seconds", (int) Math.Ceiling(remaining.TotalSeconds)));
        }
        else if (_lastState.OnCooldown && _lastState.CooldownEndTime != null)
        {
            var remaining = _lastState.CooldownEndTime.Value - now;
            if (remaining < TimeSpan.Zero)
                remaining = TimeSpan.Zero;

            TimerLabel.Text = Loc.GetString("n14-expedition-timer-cooldown",
                ("time", $"{remaining.Minutes:D2}:{remaining.Seconds:D2}"));
        }
        else
        {
            TimerPanel.Visible = false;
        }
    }

    /// <summary>Open the dedicated expedition briefing/confirm window.</summary>
    private void ShowConfirmation()
    {
        // Don't open a second window if one is already showing
        if (_confirmWindow is { Disposed: false })
            return;

        _confirmWindow = new N14ExpeditionConfirmWindow();
        LaunchButton.Disabled = true;

        // Track whether the player made an explicit choice (prevent double-action from OnClose)
        var decided = false;

        _confirmWindow.OnProceed += () =>
        {
            decided = true;
            _confirmWindow = null;
            if (_selectedTierId != null)
                OnLaunchExpedition?.Invoke(_selectedTierId);
        };

        _confirmWindow.OnCancel += () =>
        {
            decided = true;
            _confirmWindow = null;
            ReEnableLaunch();
        };

        // Closing via window X-button should also cancel
        _confirmWindow.OnClose += () =>
        {
            if (!decided)
            {
                _confirmWindow = null;
                ReEnableLaunch();
            }
        };

        _confirmWindow.OpenCentered();
    }

    /// <summary>Re-enable the launch button if the board is still idle.</summary>
    private void ReEnableLaunch()
    {
        if (_lastState is { ExpeditionActive: false, OnCooldown: false, LaunchEndTime: null }
            && _selectedTierId != null)
        {
            LaunchButton.Disabled = false;
        }
    }
}
