using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Misfits.Expeditions;

/// <summary>
/// Dedicated confirmation window shown before launching an expedition.
/// Displays the full briefing with Proceed / Do Not Proceed buttons
/// so the text is never clipped by the main board window layout.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class N14ExpeditionConfirmWindow : FancyWindow
{
    /// <summary>Fires when the player clicks Proceed.</summary>
    public event Action? OnProceed;

    /// <summary>Fires when the player clicks Do Not Proceed.</summary>
    public event Action? OnCancel;

    public N14ExpeditionConfirmWindow()
    {
        RobustXamlLoader.Load(this);

        // Build the message in code so actual newlines are used.
        // FromMarkupPermissive chokes on the literal \n sequences returned by
        // FTL, causing only the first bold line to render. #Misfits Fix
        var msg = new FormattedMessage();
        msg.AddMarkup("[bold][color=red]ALPHA TEST: Expeditions are dangerous.[/color][/bold]");
        msg.AddText(
            "\n\nUpon joining an expedition, if you die in an expedition you may not be recovered when the time runs out."
            + "\n\nUnderground expeditions last fifteen minutes due to their size."
            + "\nSurface expeditions last thirty minutes due to their size."
            + "\n\nUpon joining an expedition, you have a green marker, and there are more green markers around the map that signify your return from the expedition."
            + "\n\nItems you have with you in a 3x3 proximity within the green marker will return with you from the expedition."
            + "\n\nUpon clicking confirm, those around the expedition board will be teleported alongside you with the expedition."
            + "\n\nEach faction has their own specific expedition start location, and if a faction has more members than say, wastelanders, wastelanders also follow to the location of whichever faction has majority members for expedition start location."
            + "\n\nALL FACTIONS inside expeditions are automatically at war. Remember who came with you, and who did not."
            + "\n\nYou may already have familiarity with some of the grids you are teleporting to.");
        ConfirmWarning.SetMessage(msg);

        // Fire event BEFORE Close() so subscribers act before OnClose triggers.
        ConfirmProceedButton.OnPressed += _ =>
        {
            OnProceed?.Invoke();
            Close();
        };

        ConfirmCancelButton.OnPressed += _ =>
        {
            OnCancel?.Invoke();
            Close();
        };
    }
}
