using Content.Client.UserInterface.Controls;
using Content.Shared._Misfits.Medical.Cryogenics;
using Content.Shared.FixedPoint;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Client._Misfits.Medical.Cryogenics;

[GenerateTypedNameReferences]
public sealed partial class MisfitsCryoPodWindow : FancyWindow
{
    private static readonly (string Label, int Amount)[] AmountOptions =
    {
        ("1", 1), ("5", 5), ("10", 10), ("25", 25), ("50", 50),
    };

    private const float DosageStep = 0.5f;

    public event Action<string, FixedPoint2>? OnDeposit;
    public event Action? OnEject;
    public event Action<FixedPoint2>? OnSetTransferAmount;

    private readonly ButtonGroup _amountGroup = new();
    private FixedPoint2 _selectedAmount = 5;
    private FixedPoint2 _transferAmount = 2;
    private FixedPoint2 _minTransferAmount;
    private FixedPoint2 _maxTransferAmount = FixedPoint2.MaxValue;

    public MisfitsCryoPodWindow()
    {
        RobustXamlLoader.Load(this);

        EjectButton.OnPressed += _ => OnEject?.Invoke();

        DosageDownButton.OnPressed += _ =>
        {
            var next = FixedPoint2.Clamp(_transferAmount - DosageStep, _minTransferAmount, _maxTransferAmount);
            OnSetTransferAmount?.Invoke(next);
        };
        DosageUpButton.OnPressed += _ =>
        {
            var next = FixedPoint2.Clamp(_transferAmount + DosageStep, _minTransferAmount, _maxTransferAmount);
            OnSetTransferAmount?.Invoke(next);
        };

        foreach (var (label, amount) in AmountOptions)
        {
            var button = new Button { Text = label, ToggleMode = true, Group = _amountGroup };
            if (amount == 5)
                button.Pressed = true;
            button.OnPressed += _ => _selectedAmount = amount;
            AmountRow.AddChild(button);
        }
    }

    public void UpdateState(MisfitsCryoPodBoundUserInterfaceState state)
    {
        HealthPanel.Populate(state.HealthScan);

        TemperatureLabel.Text = $"{state.PatientTemperature:F0}K (target {state.TargetTemperature:F0}K)";
        TemperatureLabel.FontColorOverride = state.PatientTemperature <= state.TargetTemperature + 5f
            ? new Color(0.55f, 0.75f, 1f)
            : Color.White;

        _transferAmount = state.TransferAmount;
        _minTransferAmount = state.MinTransferAmount;
        _maxTransferAmount = state.MaxTransferAmount;
        DosageLabel.Text = $"{state.TransferAmount}u/cycle";

        PatientReagentContainer.RemoveAllChildren();
        foreach (var reagent in state.PatientReagents)
            PatientReagentContainer.AddChild(BuildReadonlyRow(reagent));
        if (state.PatientReagents.Length == 0)
            PatientReagentContainer.AddChild(new Label { Text = "Nothing detected." });

        ChamberContainer.RemoveAllChildren();
        foreach (var reagent in state.ChamberReagents)
            ChamberContainer.AddChild(BuildReadonlyRow(reagent));
        if (state.ChamberReagents.Length == 0)
            ChamberContainer.AddChild(new Label { Text = "Empty." });

        BeakerNameLabel.Text = state.HasBeaker ? state.BeakerName : "none inserted";
        EjectButton.Disabled = !state.HasBeaker;

        BeakerContainer.RemoveAllChildren();
        if (!state.HasBeaker)
        {
            BeakerContainer.AddChild(new Label { Text = "Insert a beaker to deposit reagents." });
        }
        else if (state.BeakerReagents.Length == 0)
        {
            BeakerContainer.AddChild(new Label { Text = "Beaker is empty." });
        }
        else
        {
            foreach (var reagent in state.BeakerReagents)
                BeakerContainer.AddChild(BuildDepositRow(reagent));
        }
    }

    private static Control BuildReadonlyRow(MisfitsCryoReagentReadout reagent)
    {
        var marker = new PanelContainer
        {
            MinWidth = 4,
            Margin = new Thickness(0, 1, 6, 1),
            PanelOverride = new StyleBoxFlat { BackgroundColor = reagent.Color },
        };

        return new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            VerticalAlignment = VAlignment.Center,
            Margin = new Thickness(2),
            Children =
            {
                marker,
                new Label { Text = reagent.Name, HorizontalExpand = true },
                new Label { Text = $"{reagent.Quantity}u" },
            },
        };
    }

    private Control BuildDepositRow(MisfitsCryoReagentReadout reagent)
    {
        var marker = new PanelContainer
        {
            MinWidth = 4,
            Margin = new Thickness(0, 1, 6, 1),
            PanelOverride = new StyleBoxFlat { BackgroundColor = reagent.Color },
        };

        var button = new Button { Text = "Deposit" };
        button.OnPressed += _ => OnDeposit?.Invoke(reagent.ReagentId, _selectedAmount);

        return new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            VerticalAlignment = VAlignment.Center,
            Margin = new Thickness(2),
            Children =
            {
                marker,
                new Label { Text = reagent.Name, HorizontalExpand = true },
                new Label { Text = $"{reagent.Quantity}u", Margin = new Thickness(6, 0) },
                button,
            },
        };
    }
}
