// #Misfits Change: Floating round-end countdown widget.
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Misfits.RoundTimer;

[GenerateTypedNameReferences]
public sealed partial class RoundTimerWidget : UIWidget
{
    public RoundTimerWidget()
    {
        RobustXamlLoader.Load(this);
    }
}
