// SPDX-License-Identifier: AGPL-3.0-or-later
// Adapted from Goob Station / Trauma Station

using Content.Client.UserInterface.Controls;
using Content.Shared.Construction.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Utility;
using Robust.Shared.Prototypes;

namespace Content.Client._Misfits.Factory.UI;

[GenerateTypedNameReferences]
public sealed partial class ConstructorRecipeWindow : FancyWindow
{
    public event Action<ConstructionPrototype>? RecipeSelected;

    private readonly List<ConstructionPrototype> _recipes = new();

    public ConstructorRecipeWindow()
    {
        RobustXamlLoader.Load(this);

        SearchLine.OnTextChanged += _ => Populate();
        RecipeList.OnItemSelected += args =>
        {
            if (RecipeList[args.ItemIndex].Metadata is ConstructionPrototype recipe)
                RecipeSelected?.Invoke(recipe);
            Close();
        };
    }

    public void SetRecipes(IReadOnlyList<ConstructionPrototype> recipes)
    {
        _recipes.Clear();
        _recipes.AddRange(recipes);
        Populate();
    }

    private void Populate()
    {
        var search = SearchLine.Text.Trim();
        RecipeList.Clear();

        foreach (var recipe in _recipes)
        {
            if (!string.IsNullOrEmpty(search) &&
                !recipe.Name.Contains(search, StringComparison.InvariantCultureIgnoreCase))
                continue;

            RecipeList.Add(new ItemList.Item(RecipeList)
            {
                Metadata = recipe,
                Text = recipe.Name,
                Icon = recipe.Icon.Frame0(),
                TooltipEnabled = true,
                TooltipText = recipe.Description
            });
        }
    }
}
