using Content.Client._Shitmed.UserInterface.Systems.PartStatus;
using Content.Shared.Nutrition.Components;
using Content.Shared._Shitmed.Targeting;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Timing;
using Robust.Shared.Utility;
using System.Linq;

namespace Content.Client._Shitmed.UserInterface.Systems.PartStatus.Widgets;

[GenerateTypedNameReferences]
public sealed partial class PartStatusControl : UIWidget
{
    private readonly Dictionary<TargetBodyPart, TextureRect> _partStatusControls;
    private readonly PartStatusUIController _controller;
    private readonly IEntityManager _entityManager;
    private readonly IPlayerManager _playerManager;
    private bool _needsWarningTint;

    public PartStatusControl()
    {
        RobustXamlLoader.Load(this);

        _controller = UserInterfaceManager.GetUIController<PartStatusUIController>();
        _entityManager = IoCManager.Resolve<IEntityManager>();
        _playerManager = IoCManager.Resolve<IPlayerManager>();
        _partStatusControls = new Dictionary<TargetBodyPart, TextureRect>
        {
            { TargetBodyPart.Head, DollHead },
            { TargetBodyPart.Torso, DollTorso },
            { TargetBodyPart.Groin, DollGroin },
            { TargetBodyPart.LeftArm, DollLeftArm },
            { TargetBodyPart.LeftHand, DollLeftHand },
            { TargetBodyPart.RightArm, DollRightArm },
            { TargetBodyPart.RightHand, DollRightHand },
            { TargetBodyPart.LeftLeg, DollLeftLeg },
            { TargetBodyPart.LeftFoot, DollLeftFoot },
            { TargetBodyPart.RightLeg, DollRightLeg },
            { TargetBodyPart.RightFoot, DollRightFoot }
        };
    }

    public void SetTextures(Dictionary<TargetBodyPart, TargetIntegrity> state)
    {
        foreach (var (bodyPart, integrity) in state)
        {
            string enumName = Enum.GetName(typeof(TargetBodyPart), bodyPart) ?? "Unknown";
            int enumValue = (int) integrity;
            var texture = new SpriteSpecifier.Rsi(new ResPath($"/Textures/_Shitmed/Interface/Targeting/Status/{enumName.ToLowerInvariant()}.rsi"), $"{enumName.ToLowerInvariant()}_{enumValue}");
            _partStatusControls[bodyPart].Texture = _controller.GetTexture(texture);
        }
    }

    public void SetVisible(bool visible) => this.Visible = visible;

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        var warningTint = ShouldShowNeedsWarningTint();
        if (warningTint == _needsWarningTint)
            return;

        _needsWarningTint = warningTint;
        var color = warningTint ? Color.Yellow : Color.White;

        foreach (var control in _partStatusControls.Values)
        {
            control.Modulate = color;
        }
    }

    private bool ShouldShowNeedsWarningTint()
    {
        var entity = _playerManager.LocalEntity;
        if (entity is null)
            return false;

        if (_entityManager.TryGetComponent(entity.Value, out HungerComponent? hunger) && hunger.CurrentThreshold == HungerThreshold.Dead)
            return true;

        return _entityManager.TryGetComponent(entity.Value, out ThirstComponent? thirst) && thirst.CurrentThirstThreshold == ThirstThreshold.Dead;
    }

}
