// #Misfits Add - Code-behind for the Raid Requests admin control. Embedded by BwoinkControl
// when an admin clicks the Raid tab. Mirrors the bwoink/mhelp pattern: list on the left,
// details + admin-action form on the right. Approve/Deny require a non-empty comment.

using System.Linq;
using Content.Shared._Misfits.RaidRequest;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Misfits.RaidRequest.UI;

[GenerateTypedNameReferences]
public sealed partial class RaidRequestAdminControl : Control
{
    private enum FilterMode { Pending, Decided, All }

    private readonly RaidRequestClientSystem _system;
    private FilterMode _filter = FilterMode.Pending;
    private int? _selectedId;
    private List<RaidRequestEntry> _all = new();

    public RaidRequestAdminControl()
    {
        RobustXamlLoader.Load(this);

        _system = IoCManager.Resolve<IEntityManager>().System<RaidRequestClientSystem>();
        _system.AdminControl = this;

        // Filter buttons: radio behavior.
        FilterPending.OnPressed += _ => SetFilter(FilterMode.Pending);
        FilterDecided.OnPressed += _ => SetFilter(FilterMode.Decided);
        FilterAll.OnPressed     += _ => SetFilter(FilterMode.All);

        ApproveButton.OnPressed += _ => Decide(true);
        DenyButton.OnPressed    += _ => Decide(false);
        // #Misfits Add - End Raid sends an explicit end-message; no comment required.
        EndRaidButton.OnPressed += _ => EndRaid();

        // Push subscribe + render whatever the system already cached so we don't sit blank
        // until a server update arrives.
        _system.SendAdminSubscribe();
        UpdateList(_system.AdminRequests);
    }

    protected override void Dispose(bool disposing)
    {
        if (disposing && _system.AdminControl == this)
            _system.AdminControl = null;
        base.Dispose(disposing);
    }

    /// <summary>Called by <see cref="RaidRequestClientSystem"/> whenever the snapshot changes.</summary>
    public void UpdateList(IReadOnlyList<RaidRequestEntry> requests)
    {
        _all = requests.ToList();
        Rebuild();
    }

    public void ShowDecisionResult(int requestId, bool success, string message)
    {
        if (_selectedId != requestId)
            return;
        var color = success ? "#32CD32" : "#FF4500";
        DecisionResultLabel.SetMarkup($"[color={color}]{FormattedMessage.EscapeText(message)}[/color]");
    }

    private void SetFilter(FilterMode mode)
    {
        _filter = mode;
        FilterPending.Pressed = mode == FilterMode.Pending;
        FilterDecided.Pressed = mode == FilterMode.Decided;
        FilterAll.Pressed     = mode == FilterMode.All;
        Rebuild();
    }

    private void Rebuild()
    {
        // Footer pending count is always the unfiltered total — admins want to see it at a glance.
        var pendingCount = _all.Count(e => e.Status == RaidRequestStatus.Pending);
        PendingCountLabel.Text = pendingCount > 0
            ? Loc.GetString("raid-request-pending-count", ("count", pendingCount))
            : Loc.GetString("raid-request-no-pending");

        // Filter the list view.
        // #Misfits Tweak - "Decided" now includes Active and Concluded so admins can review live and ended raids alongside denied ones.
        var filtered = _filter switch
        {
            FilterMode.Pending => _all.Where(e => e.Status == RaidRequestStatus.Pending),
            FilterMode.Decided => _all.Where(e => e.Status is RaidRequestStatus.Approved
                                                            or RaidRequestStatus.Active
                                                            or RaidRequestStatus.Denied
                                                            or RaidRequestStatus.Concluded),
            _                  => _all.AsEnumerable(),
        };

        RequestList.RemoveAllChildren();

        var anySelected = false;
        foreach (var entry in filtered.OrderByDescending(e => e.Id))
        {
            var row = BuildRow(entry);
            RequestList.AddChild(row);
            if (_selectedId == entry.Id)
                anySelected = true;
        }

        if (RequestList.ChildCount == 0)
        {
            RequestList.AddChild(new Label
            {
                Text = Loc.GetString("raid-request-list-empty"),
                FontColorOverride = Color.Gray,
                Margin = new Thickness(8, 8),
            });
        }

        // If the previously selected request is gone or filtered out, clear the right pane.
        if (!anySelected)
        {
            _selectedId = null;
            RenderDetails(null);
        }
        else
        {
            // Refresh details with the latest copy of the selected entry.
            RenderDetails(_all.FirstOrDefault(e => e.Id == _selectedId));
        }
    }

    private Control BuildRow(RaidRequestEntry entry)
    {
        var (statusColor, statusName) = StatusVisuals(entry.Status);
        var btn = new Button
        {
            HorizontalExpand = true,
            ToggleMode       = true,
            Pressed          = _selectedId == entry.Id,
            Text             = $"#{entry.Id}  [{statusName}]\n" +
                               $"{(entry.IsIndividual ? entry.RequesterCharacterName : RaidRequestConfig.FactionDisplayName(entry.RequesterFaction))} " +
                               $"→ {GetTargetDisplayName(entry)}",
            Modulate         = statusColor,
        };
        btn.OnPressed += _ =>
        {
            _selectedId = entry.Id;
            // Refresh button states so only the new selection looks pressed.
            Rebuild();
        };
        return btn;
    }

    private void RenderDetails(RaidRequestEntry? entry)
    {
        if (entry == null)
        {
            DetailsTitle.Text     = Loc.GetString("raid-request-no-selection");
            DetailsBody.SetMarkup(string.Empty);
            CommentLabel.Visible      = false;
            CommentEdit.Visible       = false;
            DecisionButtonRow.Visible = false;
            DecisionResultLabel.SetMarkup(string.Empty);
            return;
        }

        var (statusColor, statusName) = StatusVisuals(entry.Status);
        var hex = $"#{(byte)(statusColor.R * 255):X2}{(byte)(statusColor.G * 255):X2}{(byte)(statusColor.B * 255):X2}";

        DetailsTitle.Text = $"#{entry.Id} — {statusName}";

        var who = entry.IsIndividual
            ? $"{entry.RequesterCharacterName} (individual: {entry.RequesterUserName})"
            : $"{RaidRequestConfig.FactionDisplayName(entry.RequesterFaction)} via {entry.RequesterCharacterName} ({entry.RequesterUserName})";

        var body = $"[color={hex}][bold]{statusName}[/bold][/color]\n\n" +
                   $"[bold]Requester:[/bold] {FormattedMessage.EscapeText(who)}\n" +
                   $"[bold]Job:[/bold] {FormattedMessage.EscapeText(entry.RequesterJob)}\n" +
                   $"[bold]Target:[/bold] {FormattedMessage.EscapeText(GetTargetDisplayName(entry))}\n";

        if (!string.IsNullOrWhiteSpace(entry.LocationNotes))
            body += $"[bold]Location:[/bold] {FormattedMessage.EscapeText(entry.LocationNotes)}\n";

        body += $"[bold]Submitted:[/bold] {entry.CreatedAtUtc.ToLocalTime():HH:mm:ss}\n\n" +
                $"[bold]Reason:[/bold]\n{FormattedMessage.EscapeText(entry.Reason)}";

        if (entry.Status != RaidRequestStatus.Pending)
        {
            body += $"\n\n[bold]Decided by:[/bold] {FormattedMessage.EscapeText(entry.AdminUserName ?? "(unknown)")}";
            if (entry.DecidedAtUtc is { } dt)
                body += $" at {dt.ToLocalTime():HH:mm:ss}";
            if (!string.IsNullOrWhiteSpace(entry.AdminComment))
                body += $"\n[bold]Remarks:[/bold] {FormattedMessage.EscapeText(entry.AdminComment)}";
        }

        // #Misfits Add - Show conclusion metadata for ended raids (manual or auto-expiry).
        if (entry.Status == RaidRequestStatus.Concluded)
        {
            body += $"\n\n[bold]Concluded by:[/bold] {FormattedMessage.EscapeText(entry.ConcludedByAdmin ?? "(unknown)")}";
            if (entry.ConcludedAtUtc is { } ct)
                body += $" at {ct.ToLocalTime():HH:mm:ss}";
        }

        DetailsBody.SetMarkup(body);

        // Show the action form only for pending requests.
        var pending = entry.Status == RaidRequestStatus.Pending;
        CommentLabel.Visible      = pending;
        CommentEdit.Visible       = pending;
        DecisionButtonRow.Visible = pending;
        // #Misfits Add - End Raid button is only meaningful for currently-Approved raids.
        EndRaidRow.Visible        = entry.Status == RaidRequestStatus.Approved
                                 || entry.Status == RaidRequestStatus.Active;
        if (!pending)
            CommentEdit.Text = string.Empty;

        DecisionResultLabel.SetMarkup(string.Empty);
    }

    private void Decide(bool approve)
    {
        if (_selectedId is not { } id)
            return;
        var comment = CommentEdit.Text.Trim();
        if (string.IsNullOrWhiteSpace(comment))
        {
            DecisionResultLabel.SetMarkup(
                $"[color=#FF4500]{FormattedMessage.EscapeText(Loc.GetString("raid-request-comment-required"))}[/color]");
            return;
        }
        _system.SendDecision(id, approve, comment);
    }

    // #Misfits Add - Manual end-raid; no comment required since the raid was already approved.
    private void EndRaid()
    {
        if (_selectedId is not { } id)
            return;
        _system.SendEndRaid(id);
    }

    private static (Color color, string name) StatusVisuals(RaidRequestStatus status) => status switch
    {
        RaidRequestStatus.Pending   => (Color.FromHex("#FFAA00"), "PENDING"),
        RaidRequestStatus.Approved  => (Color.FromHex("#A8E060"), "APPROVED — PREP"), // #Misfits Tweak - 5-min prep before raid goes live.
        RaidRequestStatus.Active    => (Color.FromHex("#3CFF40"), "ACTIVE"), // #Misfits Add - overlay live, 15-min engagement window.
        RaidRequestStatus.Denied    => (Color.FromHex("#FF4040"), "DENIED"),
        RaidRequestStatus.Unclaimed => (Color.FromHex("#888888"), "UNCLAIMED"),
        RaidRequestStatus.Concluded => (Color.FromHex("#7B68EE"), "CONCLUDED"), // #Misfits Add - slate blue distinguishes ended raids.
        _                           => (Color.White,              status.ToString()),
    };

    private static string GetTargetDisplayName(RaidRequestEntry entry)
    {
        if (!string.IsNullOrWhiteSpace(entry.TargetDisplayName))
            return entry.TargetDisplayName;

        return entry.TargetKind == RaidRequestTargetKind.Faction
            ? RaidRequestConfig.FactionDisplayName(entry.TargetId)
            : $"Group {entry.TargetId}";
    }
}
