// #Misfits Add - Code-behind for the peer-faction approval popup. Renders incoming raid
// request context and lets the target faction's highest-ranking online member YES/NO it.

using Content.Client.UserInterface.Controls;
using Content.Shared._Misfits.RaidRequest;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Misfits.RaidRequest.UI;

[GenerateTypedNameReferences]
public sealed partial class RaidRequestPeerDecisionWindow : FancyWindow
{
    /// <summary>(approve, comment)</summary>
    public event Action<bool, string>? OnDecided;

    public int RequestId { get; private set; }

    public RaidRequestPeerDecisionWindow()
    {
        RobustXamlLoader.Load(this);

        ApproveButton.OnPressed += _ =>
        {
            LockButtons();
            OnDecided?.Invoke(true, CommentEdit.Text);
        };
        DenyButton.OnPressed += _ =>
        {
            LockButtons();
            OnDecided?.Invoke(false, CommentEdit.Text);
        };
    }

    public void Populate(RaidRequestEntry entry)
    {
        RequestId = entry.Id;

        var requesterFaction = RaidRequestConfig.FactionDisplayName(entry.RequesterFaction);
        var targetFaction    = GetTargetDisplayName(entry);

        HeaderLabel.SetMarkup(
            $"[color=#FF6655][bold]{FormattedMessage.EscapeText(Loc.GetString("raid-request-peer-header", ("faction", requesterFaction), ("target", targetFaction)))}[/bold][/color]");

        FromLabel.SetMarkup(
            $"[color=#FFCC60]{FormattedMessage.EscapeText(requesterFaction)}[/color] " +
            $"[color=#CCCCCC]via {FormattedMessage.EscapeText(entry.RequesterCharacterName)} ({FormattedMessage.EscapeText(entry.RequesterJob ?? "?")})[/color]");

        LocationLabel.SetMarkup(string.IsNullOrWhiteSpace(entry.LocationNotes)
            ? $"[color=#888888]{FormattedMessage.EscapeText(Loc.GetString("raid-request-peer-location-unset"))}[/color]"
            : $"[color=#CCCCCC]{FormattedMessage.EscapeText(entry.LocationNotes)}[/color]");

        ReasonLabel.SetMarkup(
            $"[color=#CCCCCC]{FormattedMessage.EscapeText(entry.Reason)}[/color]");

        StatusLabel.SetMarkup(string.Empty);
    }

    private static string GetTargetDisplayName(RaidRequestEntry entry)
    {
        if (!string.IsNullOrWhiteSpace(entry.TargetDisplayName))
            return entry.TargetDisplayName;

        return entry.TargetKind == RaidRequestTargetKind.Faction
            ? RaidRequestConfig.FactionDisplayName(entry.TargetId)
            : $"Group {entry.TargetId}";
    }

    public void ShowFailure(string message)
    {
        // Re-arm so the leader can retry if the failure is transient.
        ApproveButton.Disabled = false;
        DenyButton.Disabled    = false;
        StatusLabel.SetMarkup(
            $"[color=#FF6655]{FormattedMessage.EscapeText(message)}[/color]");
    }

    private void LockButtons()
    {
        ApproveButton.Disabled = true;
        DenyButton.Disabled    = true;
    }
}
