// #Misfits Add - Code-behind for the /raid requester window. Pure UI: shows eligibility,
// gathers the form fields, enforces a confirm-press flow on Submit, and renders the
// player's own requests this round. Validation feedback comes from the server.

using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._Misfits.RaidRequest;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Misfits.RaidRequest.UI;

[GenerateTypedNameReferences]
public sealed partial class RaidRequestWindow : FancyWindow
{
    /// <summary>(targetFactionId, locationNotes, reason)</summary>
    public event Action<(RaidRequestTargetKind Kind, string Id), string, string>? OnSubmit;

    private readonly List<(RaidRequestTargetKind Kind, string Display, string Id)> _targetItems = new();
    private bool _confirmPending;

    public RaidRequestWindow()
    {
        RobustXamlLoader.Load(this);

        SubmitButton.OnPressed += _ => OnSubmitPressed();
        TargetSelector.OnItemSelected += args =>
        {
            TargetSelector.SelectId(args.Id);
            ResetConfirm();
        };

        // Re-arm confirm whenever fields are edited so the player must re-confirm after a change.
        ReasonEdit.OnTextChanged   += _ => ResetConfirm();
        LocationEdit.OnTextChanged += _ => ResetConfirm();
    }

    public void UpdateState(RaidRequestPanelDataMsg msg)
    {
        // Faction header
        MyFactionLabel.Text = msg.MyFactionId == null
            ? Loc.GetString("raid-request-no-faction")
            : msg.MyFactionDisplay + (msg.MyFactionIsIndividualTier
                ? $" {Loc.GetString("raid-request-individual-suffix")}"
                : "");

        // Eligibility banner
        if (!msg.CanSubmit)
        {
            EligibilityLabel.SetMarkup(
                $"[color=#FF6655]{FormattedMessage.EscapeText(msg.IneligibleReason ?? Loc.GetString("raid-request-not-eligible"))}[/color]");
        }
        else if (msg.MyFactionIsIndividualTier)
        {
            EligibilityLabel.SetMarkup(
                $"[color=#80CCFF]{FormattedMessage.EscapeText(Loc.GetString("raid-request-individual-banner"))}[/color]");
        }
        else
        {
            EligibilityLabel.SetMarkup(string.Empty);
        }

        // Target dropdown
        _targetItems.Clear();
        TargetSelector.Clear();
        foreach (var t in msg.TargetOptions)
        {
            _targetItems.Add((t.Kind, t.DisplayName, t.Id));
            TargetSelector.AddItem(t.DisplayName);
        }

        // Disable submit if no targets or not eligible.
        var canEnable = msg.CanSubmit && _targetItems.Count > 0;
        SubmitButton.Disabled    = !canEnable;
        TargetSelector.Disabled  = !canEnable;
        LocationEdit.Editable    = canEnable;
        ReasonEdit.Editable      = canEnable;
        ResetConfirm();

        // My requests list
        MyRequestsContainer.RemoveAllChildren();
        if (msg.MyRequests.Count == 0)
        {
            MyRequestsContainer.AddChild(new Label
            {
                Text = Loc.GetString("raid-request-no-my-requests"),
                FontColorOverride = Color.Gray,
                Margin = new Thickness(4, 2),
            });
        }
        else
        {
            foreach (var req in msg.MyRequests.OrderByDescending(r => r.Id))
                MyRequestsContainer.AddChild(BuildMyRequestRow(req));
        }

        ClearResult();
    }

    public void ShowResult(bool success, string message)
    {
        var color = success ? "#32CD32" : "#FF4500";
        ResultLabel.SetMarkup($"[color={color}]{FormattedMessage.EscapeText(message)}[/color]");
    }

    private void ClearResult() => ResultLabel.SetMarkup(string.Empty);

    private void OnSubmitPressed()
    {
        if (_targetItems.Count == 0)
            return;
        var idx = TargetSelector.SelectedId;
        if (idx < 0 || idx >= _targetItems.Count)
            return;

        var reason = ReasonEdit.Text.Trim();
        if (reason.Split(' ', StringSplitOptions.RemoveEmptyEntries).Length < RaidRequestConfig.MinReasonWords)
        {
            ShowResult(false, Loc.GetString("raid-request-reason-too-short",
                ("min", RaidRequestConfig.MinReasonWords)));
            return;
        }

        if (!_confirmPending)
        {
            _confirmPending = true;
            SubmitButton.Text     = Loc.GetString("raid-request-submit-confirm");
            SubmitButton.Modulate = Color.OrangeRed;
            ShowResult(false, Loc.GetString("raid-request-confirm-prompt"));
            return;
        }

        var target = _targetItems[idx];
        var location = LocationEdit.Text.Trim();
        OnSubmit?.Invoke((target.Kind, target.Id), location, reason);
        ResetConfirm();
    }

    private void ResetConfirm()
    {
        _confirmPending = false;
        SubmitButton.Text     = Loc.GetString("raid-request-submit-button");
        SubmitButton.Modulate = Color.White;
    }

    private static Control BuildMyRequestRow(RaidRequestEntry req)
    {
        var statusColor = req.Status switch
        {
            RaidRequestStatus.Pending   => "#FFAA00",
            RaidRequestStatus.Approved  => "#A8E060", // #Misfits Tweak - prep phase (5-min countdown to Active).
            RaidRequestStatus.Active    => "#3CFF40", // #Misfits Add - overlay live; engagement window open.
            RaidRequestStatus.Denied    => "#FF4040",
            RaidRequestStatus.Unclaimed => "#888888",
            RaidRequestStatus.Concluded => "#7B68EE", // #Misfits Add - matches admin panel slate-blue.
            _                           => "#FFFFFF",
        };
        var box = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
            Margin = new Thickness(4, 2),
        };
        var headerLabel = new RichTextLabel { HorizontalExpand = true };
        headerLabel.SetMarkup(
            $"[color={statusColor}][bold]#{req.Id} {req.Status.ToString().ToUpperInvariant()}[/bold][/color] " +
            $"[color=#CCCCCC]→ {FormattedMessage.EscapeText(GetTargetDisplayName(req))}[/color]");
        box.AddChild(headerLabel);

        if (!string.IsNullOrWhiteSpace(req.AdminComment))
        {
            var commentLabel = new RichTextLabel { HorizontalExpand = true };
            commentLabel.SetMarkup(
                $"[italic][color=#AAAAAA]{FormattedMessage.EscapeText("Admin: " + (req.AdminUserName ?? "?") + " — " + req.AdminComment)}[/color][/italic]");
            box.AddChild(commentLabel);
        }
        return box;
    }

    private static string GetTargetDisplayName(RaidRequestEntry req)
    {
        if (!string.IsNullOrWhiteSpace(req.TargetDisplayName))
            return req.TargetDisplayName;

        return req.TargetKind == RaidRequestTargetKind.Faction
            ? RaidRequestConfig.FactionDisplayName(req.TargetId)
            : $"Group {req.TargetId}";
    }
}
